<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Support du cours de chimie générale | Maturité gymnasiale">

<title>14&nbsp; Les gaz parfaits – Cours de chimie générale</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./150-cinetique.html" rel="next">
<link href="./130-stoechiometrie.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-05ad7de8ae34bb1016f06e23b5e9a5a9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script>
window.MathJax = {
  loader: { load: ['[tex]/mhchem', '[tex]/cancel'] },
  tex: { packages: { '[+]': ['mhchem', 'cancel'] } }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./140-gaz-parfaits.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Les gaz parfaits</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Cours de chimie générale</a> 
        <div class="sidebar-tools-main">
    <a href="./chimie-generale.pdf" title="Télécharger le PDF" class="quarto-navigation-tool px-1" aria-label="Télécharger le PDF" target="_blank"><i class="bi bi-file-earmark-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Préambule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-etats-de-la-matiere.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Les états de la matière</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-melanges-corps-purs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Mélanges et corps purs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-historique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Historique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./50-atome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">L’atome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./60-tableau-periodique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Le tableau périodique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./70-liaisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Molécules et liaisons chimiques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./80-molecules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Géométrie moléculaire et polarité</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./90-nomenclature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Nomenclature</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./100-solutions-electrolytes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Solutions et électrolytes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./110-reactions-chimiques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Réactions chimiques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./120-types-reactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Types de réactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./130-stoechiometrie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Calculs stœchiométriques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./140-gaz-parfaits.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Les gaz parfaits</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./150-cinetique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cinétique chimique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./160-equilibres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">L’équilibre chimique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./170-acides-bases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Les acides et les bases</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./180-ph-potentiel-hydrogene.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Le pH ou potentiel hydrogène</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./190-produit-solubilite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Le produit de solubilité</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./200-oxydoreductions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Les réactions d’oxydoréduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./210-electrochimie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Électrochimie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./220-thermochimie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Thermochimie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./230-thermodynamique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Thermodynamique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliographie</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#la-théorie-cinétique-des-gaz" id="toc-la-théorie-cinétique-des-gaz" class="nav-link active" data-scroll-target="#la-théorie-cinétique-des-gaz"><span class="header-section-number">14.1</span> La théorie cinétique des gaz</a></li>
  <li><a href="#les-lois-simples-des-gaz" id="toc-les-lois-simples-des-gaz" class="nav-link" data-scroll-target="#les-lois-simples-des-gaz"><span class="header-section-number">14.2</span> Les lois simples des gaz</a></li>
  <li><a href="#la-loi-des-gaz-parfaits" id="toc-la-loi-des-gaz-parfaits" class="nav-link" data-scroll-target="#la-loi-des-gaz-parfaits"><span class="header-section-number">14.3</span> La loi des gaz parfaits</a>
  <ul class="collapse">
  <li><a href="#les-unités-des-gaz" id="toc-les-unités-des-gaz" class="nav-link" data-scroll-target="#les-unités-des-gaz"><span class="header-section-number">14.3.1</span> Les unités des gaz</a></li>
  </ul></li>
  <li><a href="#la-loi-des-pressions-partielles" id="toc-la-loi-des-pressions-partielles" class="nav-link" data-scroll-target="#la-loi-des-pressions-partielles"><span class="header-section-number">14.4</span> La loi des pressions partielles</a></li>
  <li><a href="#résumé" id="toc-résumé" class="nav-link" data-scroll-target="#résumé"><span class="header-section-number">14.5</span> Résumé</a></li>
  <li><a href="#exercices-supplémentaires" id="toc-exercices-supplémentaires" class="nav-link" data-scroll-target="#exercices-supplémentaires"><span class="header-section-number">14.6</span> Exercices supplémentaires</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Les gaz parfaits</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="objectives">
<ul>
<li>Utiliser la théorie cinétique pour expliquer le comportement des gaz et la pression.</li>
<li>Convertir les différentes unités de pression.</li>
<li>Utilisez la loi des gaz parfaits pour calculer la pression, la température, le volume ou le nombre de moles d’un gaz parfait.</li>
<li>Utilisez la loi des gaz parfaits dans les calculs stœchiométriques impliquant des réactifs ou des produits gazeux.</li>
</ul>
</div>
<section id="la-théorie-cinétique-des-gaz" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="la-théorie-cinétique-des-gaz"><span class="header-section-number">14.1</span> La théorie cinétique des gaz</h2>
<p>Les gaz se comportent très différemment des liquides et des solides. Par exemple, les gaz ont une faible densité et sont compressibles. En revanche, les liquides et les solides sont beaucoup plus denses et beaucoup moins compressibles. De plus, les gaz subissent une expansion ou une contraction beaucoup plus importantes lors de changements de la température.</p>
<p>La théorie cinétique des gaz est un groupe d’hypothèses qui expliquent le comportement et les propriétés observables des gaz :</p>
<ul>
<li><p>Les gaz sont formés de particules microscopiques. L’espace occupé par les particules est beaucoup plus petit que l’espace entre les particules. La majeure partie du volume occupé par un gaz est le vide.</p></li>
<li><p>Les particules se déplacent sans cesse en ligne droite dans toutes les directions.</p></li>
<li><p>Ces particules entrent sans cesse en collision et frappent les parois du récipient qui les renferme. Toutes les collisions se produisent sans perte d’énergie (collision élastique).</p></li>
<li><p>L’énergie cinétique moyenne des particules de gaz est proportionnelle à la température en Kelvin. Plus les particules bougent rapidement, plus leur énergie cinétique augmente, plus la température augmente.</p></li>
</ul>
<div id="fig-theorie-cinetique" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-theorie-cinetique-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/theorie-cinetique.png" class="img-fluid figure-img" style="width:20.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-theorie-cinetique-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1: Illustration du modèle de la théorie cinétique des gaz
</figcaption>
</figure>
</div>
<p>Un gaz qui obéit à toutes les hypothèses de la théorie cinétique est appelé gaz parfait (ou idéal). Dans la pratique, il n’existe pas de gaz parfaitement idéal. Dans le cas de pressions très élevées, ou à des températures très basses, ces hypothèses ne sont plus vérifiées. Cependant, en règle générale, la plupart des gaz réels présentent un comportement presque idéal dans des conditions normales.</p>
<p>Un échantillon de gaz peut être caractérisé par quatre variables :</p>
<ul>
<li>le volume <em>V</em>,</li>
<li>la température <em>T</em>,</li>
<li>la pression <em>P</em>,</li>
<li>et la quantité de matière <em>n</em> (nombre de moles).</li>
</ul>
<p>Puisque la température et la pression varient d’un endroit à l’autre sur la planète, des conditions d’étude semblables sont nécessaires afin que les scientifiques puissent comparer leurs résultats et puissent établir des lois physiques. Les scientifiques ont dû établir des normes quant aux conditions d’étude des gaz. Un ensemble de conditions a donc été établi, les <strong>CNTP</strong> et les <strong>CATP</strong> :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 12%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Température</th>
<th style="text-align: center;">Pression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Conditions <strong>Normales</strong> de Température et Pression</td>
<td style="text-align: center;">273.15 K</td>
<td style="text-align: center;"><span class="math inline">\(10^{5}\)</span> Pa</td>
</tr>
<tr class="even">
<td>Conditions <strong>Ambiantes</strong> de Température et Pression</td>
<td style="text-align: center;">298.15 K</td>
<td style="text-align: center;"><span class="math inline">\(1\)</span> bar</td>
</tr>
</tbody>
</table>
<div class="Exercise">
<p>Répondez aux questions suivantes sur la théorie cinétique des gaz.</p>
<ol type="1">
<li>Pourquoi un gaz est-il beaucoup moins dense et beaucoup plus compressible qu’un solide ou un liquide ? </li>
<li>À l’échelle microscopique, qu’est-ce qui provoque la pression exercée par un gaz sur les parois de son récipient ? </li>
<li>À quelle grandeur l’énergie cinétique moyenne des particules d’un gaz est-elle proportionnelle ? </li>
<li>Qu’appelle-t-on un « gaz parfait » ? </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>Dans un gaz, les particules sont très éloignées les unes des autres (l’essentiel du volume est du vide), alors qu’elles sont serrées dans un solide ou un liquide. On peut donc facilement les rapprocher (compressibilité) et la masse par unité de volume est faible (faible densité).</li>
<li>La pression provient des collisions incessantes des particules du gaz contre les parois du récipient.</li>
<li>À la température absolue, exprimée en kelvin.</li>
<li>Un gaz parfait est un gaz qui obéit à toutes les hypothèses de la théorie cinétique.</li>
</ol>
</div>
</section>
<section id="les-lois-simples-des-gaz" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="les-lois-simples-des-gaz"><span class="header-section-number">14.2</span> Les lois simples des gaz</h2>
<p>Dans le cas de gaz parfaits, les lois simples des gaz mettent en relation deux variables qui décrivent les gaz alors que deux autres variables sont maintenues constantes.</p>
<!--
|                                 |                  |                          |
| :-----------------------------: | ---------------- | ------------------------ |
|   $P1 \cdot V1 = P2 \cdot V2$   | T et n constants | Loi de Boyle-Mariotte    |
| $\frac{V1}{n1} = \frac{V2}{n2}$ | P et T constants | Loi d'Avogadro           |
| $\frac{P1}{n1} = \frac{P2}{n2}$ | V et T constants | Loi 1 et loi 2 combinées |
| $\frac{V1}{T1} = \frac{V2}{T2}$ | P et n constants | Loi de Charles           |
| $\frac{P1}{T1} = \frac{P2}{T2}$ | V et n constants | Loi de Gay-Lussac        |
-->
<p><span class="math display">\[
\begin{aligned}
P1 \cdot V1 &amp;= P2 \cdot V2 &amp; \text{T et n constants (Loi de Boyle-Mariotte)} \\[1em]
\frac{V1}{n1} &amp;= \frac{V2}{n2} &amp; \text{P et T constants (Loi d'Avogadro)} \\[1em]
\frac{P1}{n1} &amp;= \frac{P2}{n2} &amp; \text{V et T constants (Loi 1 et loi 2 combinées)} \\[1em]
\frac{V1}{T1} &amp;= \frac{V2}{T2} &amp; \text{P et n constants (Loi de Charles)} \\[1em]
\frac{P1}{T1} &amp;= \frac{P2}{T2} &amp; \text{V et n constants (Loi de Gay-Lussac)}
\end{aligned}
\]</span></p>
<p>En combinant les lois simples des gaz, on peut établir une relation qui permet de comparer les variables après qu’un gaz ait subi des changements, en comparant une situation initiale (1) avec une situation finale (2).</p>
<p><span class="math display">\[
\frac{P_1 \cdot V_1}{T_1} = \frac{P_2 \cdot V_2}{T_2} \qquad \text{(loi générale des gaz)}
\]</span></p>
<div class="Exercise">
<p>On remplit un ballon-sonde météorologique avec 500 l d’hélium à 25° C et une pression de 120 kPa. Le ballon s’élève à une altitude de 1850 m, où la pression est de 80 kPa et la température de 0° C. Quel sera le volume du ballon par rapport à son volume initial?</p>
</div>
<div class="Answer">
<p><span class="math display">\[
\frac{P_1 \cdot V_1}{n_1 \cdot T_1} = \frac{P_2 \cdot V_2}{n_2 \cdot T_2}
\]</span></p>
<p><span class="math display">\[
\begin{split}
    P_1 &amp;= 120\ \text{ kPa}\\
    V_1 &amp;= 500\ \text{ l}\\
    T_1 &amp;= 298\ \text{ K}\\
    n_1 &amp;= n_2
\end{split}
\qquad
\begin{split}
    P_2 &amp;= 80\ \text{ kPa}\\
    V_2 &amp;=\ ?\ \text{ l}\\
    T_2 &amp;= 273\ \text{ K}\\
    n_2 &amp;= n_1
\end{split}
\]</span></p>
<p><span class="math display">\[
\begin{split}
    V_2 &amp;= \frac{P_1 \cdot V_1 \cdot T_2}{T_1 \cdot P_2} \\
    &amp;= \frac{120\ \text{ kPa} \cdot 500\ \text{ l} \cdot 273\ \text{ K}}{298\ \text{ K} \cdot 80\ \text{ kPa}} \\
    &amp;= 687\ \text{ l}
\end{split}
\]</span></p>
</div>
<div class="Exercise">
<p>Un ballon, qui contient 18.2 g de diazote gazeux à 20° C occupe un volume de 16 l à une pression de 98.9 kPa. Quelle sera la pression si la température augmente à 50° C, que le volume diminue à 5 l et qu’on ajoute 12.8 g de dioxygène?</p>
</div>
<div class="Answer">
<p><span class="math display">\[
\begin{split}
    P_1 &amp;= 98.9\ \text{ kPa}\\
    V_1 &amp;= 16\ \text{ l}\\
    T_1 &amp;= 293\ \text{ K}\\
    n_1 &amp;= 0.65\ \text{ mol}
\end{split}
\qquad
\begin{split}
    P_2 &amp;= ?\ \text{ kPa}\\
    V_2 &amp;=\ 5\ \text{ l}\\
    T_2 &amp;= 323\ \text{ K}\\
    n_2 &amp;= 0.65 + 0.4\ \text{ mol}\\
    &amp;= 1.05\ \text{ mol}
\end{split}
\]</span></p>
<p><span class="math display">\[
\begin{split}
    \frac{P_1 \cdot V_1}{n_1 \cdot T_1} = \frac{P_2 \cdot V_2}{n_2 \cdot T_2}
\end{split}
\qquad
\begin{split}
    \Rightarrow P_2 &amp;= \frac{P_1 \cdot V_1 \cdot n_2 \cdot T_2}{n_1 \cdot T_1 \cdot V_2} \\
    &amp;= \frac{98.9\ \text{ kPa} \cdot 16\ \text{ l} \cdot 1.05\ \text{ mol} \cdot 323\ \text{ K}}{0.65\ \text{ mol} \cdot 293\ \text{ K} \cdot 5\ \text{ l}} \\
    &amp;= 563.58\ \text{ kPa}
\end{split}
\]</span></p>
</div>
</section>
<section id="la-loi-des-gaz-parfaits" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="la-loi-des-gaz-parfaits"><span class="header-section-number">14.3</span> La loi des gaz parfaits</h2>
<p>La loi générale des gaz permet de comparer les caractéristiques d’un gaz entre une situation initiale et une situation finale. Toutefois, cette formule n’est pas utile lorsqu’on veut déterminer les caractéristiques d’un gaz à un moment précis. La loi des gaz parfaits combine les lois simples des gaz en une seule expression.</p>
<p><span class="math display">\[
P \cdot V = n \cdot R \cdot T
\]</span></p>
<ul>
<li>P : pression en <span class="math inline">\(\ \mathrm{Pa}\)</span></li>
<li>V : volume en <span class="math inline">\(\ \mathrm{m^3}\)</span></li>
<li>n : quantité de matière en <span class="math inline">\(\ \mathrm{mol}\)</span></li>
<li>T : température absolue en <span class="math inline">\(\ \mathrm{K}\)</span></li>
<li>R = <strong>8.314</strong> <span class="math inline">\(\ \mathrm{\frac{J}{mol \cdot K}}\)</span> (constante des gaz parfaits)</li>
</ul>
<p>Avec cette relation, nous pouvons convertir le volume d’un gaz en quantité de matière en connaissant la pression et le température. Le volume, la pression et la température d’un gaz sont plus faciles à mesurer que la masse, et la masse molaire du gaz n’intervient pas.</p>
<div class="Exercise">
<ol type="1">
<li>Calculez le volume d’une mole de gaz aux CNTP.</li>
</ol>
<ol start="2" type="1">
<li>Calculez le volume d’une mole de gaz aux conditions de température et de pression à l’endroit où vous vous trouvez.</li>
</ol>
<ol start="3" type="1">
<li>On cherche à déterminer la valeur de la constante des gaz parfaits. Pour ce faire, à une température de 16° C et une pression de 748 mmHg, on mesure que <span class="math inline">\(5.164 \cdot 10^{-2}\)</span> mol d’un gaz occupent un volume de 1245 mL. Calculez quelle est la valeur de la constante et indiquez de quel gaz il s’agit.</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><p><span class="math display">\[
\begin{split}
P \cdot V = n \cdot R \cdot T
\end{split}
\qquad
\begin{split}
\Rightarrow V &amp;= \frac{n \cdot R \cdot T}{P} \\
&amp;= \frac{1\ \text{ mol} \cdot 8.314 \ \mathrm{\frac{J}{mol \cdot K}} \cdot 273\ \text{ K}}{1.013 \cdot 10^{5}\ \text{ Pa}} \\
&amp;= 0.0224\ \text{ m}^3 = 22.4\ \text{ l}
\end{split}
\]</span></p></li>
<li><p><span class="math display">\[
\begin{split}
\Rightarrow V &amp;= \frac{n \cdot R \cdot T}{P}
= \frac{1\ \text{ mol} \cdot 8.314 \ \mathrm{\frac{J}{mol \cdot K}} \cdot 292\ \text{ K}}{1.013 \cdot 10^{5}\ \text{ Pa}} \\
&amp;= 0.0239\ \text{ m}^3 = 23.9\ \text{ l}
\end{split}
\]</span></p></li>
<li><p><span class="math display">\[
\begin{split}
748\ \text{ mmHg} &amp;= 9.973 \cdot 10^{4}\ \text{ Pa}\\[0.33em]
1245\ mL &amp;= 1.245 \cdot 10^{-3}\ \text{ m}^3\\[0.33em]
16°\ C\ &amp;= 289.15\ \text{ K}\\
\end{split}
\qquad
\begin{split}
R = \frac{P \cdot V}{n \cdot T} &amp;= \frac{9.973 \cdot 10^{4}\ \text{ Pa} \cdot 1.245 \cdot 10^{-3}\ \text{ m}^3}{5.164 \cdot 10^{-2}\ \text{ mol} \cdot 289.15\ \text{ K}}\\[0.33em]
&amp;= 8.315 \cong 8.314 \ \mathrm{\frac{J}{mol \cdot K}}
\end{split}
\]</span></p></li>
</ol>
</div>
<section id="les-unités-des-gaz" class="level3" data-number="14.3.1">
<h3 data-number="14.3.1" class="anchored" data-anchor-id="les-unités-des-gaz"><span class="header-section-number">14.3.1</span> Les unités des gaz</h3>
<section id="le-volume" class="level4" data-number="14.3.1.1">
<h4 data-number="14.3.1.1" class="anchored" data-anchor-id="le-volume"><span class="header-section-number">14.3.1.1</span> Le volume</h4>
<p>L’unité SI de volume est le mètre cube <span class="math inline">\(m^3\)</span>. Depuis 1964, le mot “litre” <span class="math inline">\(\text{ l}\)</span> peut être utilisé . Bien qu’en dehors du système international (SI) d’unités, le litre est couramment utilisé pour caractériser un volume.</p>
<p><span class="math display">\[
\begin{split}
  1\ \mathrm{m^3} = 1000\ \mathrm{dm^3} = 1000\ \mathrm{l}
\end{split}
\qquad\qquad
\begin{split}
    1\ \mathrm{l} = 1\ \mathrm{dm^3} = 10^{-3}\ \mathrm{m^3}
\end{split}
\]</span></p>
</section>
<section id="la-température" class="level4" data-number="14.3.1.2">
<h4 data-number="14.3.1.2" class="anchored" data-anchor-id="la-température"><span class="header-section-number">14.3.1.2</span> La température</h4>
<p>Le kelvin est l’unité SI de la température thermodynamique. Le degré Celsius est également utilisé et peut exprimer une différence de température, mais lorsque l’on exprime une température absolue, on utilisera le kelvin.</p>
<p><span class="math display">\[
T_{{\mathrm{Kelvin}}}=T_{{\mathrm {Celsius}}} + 273.15
\]</span></p>
</section>
<section id="la-pression" class="level4" data-number="14.3.1.3">
<h4 data-number="14.3.1.3" class="anchored" data-anchor-id="la-pression"><span class="header-section-number">14.3.1.3</span> La pression</h4>
<p>Le “pascal” (symbole Pa) est l’unité de pression définie par la 14e Conférence Générale des Poids et Mesures de 1971. Le “pascal” est exprimé comme une force d’un newton exercée sur une surface d’un mètre carré ou comme un kilogramme par mètre par seconde carré (unités SI).</p>
<p><span class="math display">\[
1\ \mathrm{Pa} = 1\ \mathrm{\frac{N}{m^2}} = 1\ \mathrm{\frac{kg}{m \cdot s^2}}
\]</span></p>
<p>Il existe de multiples unités de pression en dehors du système international :</p>
<p><span class="math display">\[
1.013 \cdot 10^{5}\ \mathrm{Pa} =
1 \ \mathrm{atm} =
1.013 \ \mathrm{bar} =
760 \ \mathrm{mmHg}
\]</span></p>
<div class="Exercise">
<p>On rappelle les équivalences : <span class="math inline">\(1\)</span> atm <span class="math inline">\(= 1.013\cdot10^5\)</span> Pa <span class="math inline">\(= 1.013\)</span> bar <span class="math inline">\(= 760\)</span> mmHg.</p>
<ol type="1">
<li>Convertissez 2.0 atm en pascals, puis en bars. </li>
<li>Convertissez 380 mmHg en atmosphères. </li>
<li>Convertissez 202.6 kPa en atmosphères. </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><span class="math inline">\(2.0 \text{ atm} = 2.0 \cdot 1.013\cdot10^5 = 2.03\cdot10^5 \text{ Pa}\)</span> ; <span class="math inline">\(2.0 \text{ atm} = 2.0 \cdot 1.013 = 2.03 \text{ bar}\)</span>.</li>
<li><span class="math inline">\(380 \text{ mmHg} = \dfrac{380}{760} = 0.50 \text{ atm}\)</span>.</li>
<li><span class="math inline">\(202.6 \text{ kPa} = 202.6\cdot10^3 \text{ Pa}\)</span>, donc <span class="math inline">\(\dfrac{202.6\cdot10^3}{1.013\cdot10^5} = 2.0 \text{ atm}\)</span>.</li>
</ol>
</div>
</section>
</section>
</section>
<section id="la-loi-des-pressions-partielles" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="la-loi-des-pressions-partielles"><span class="header-section-number">14.4</span> La loi des pressions partielles</h2>
<p>Jusqu’à maintenant, nous n’avons traité que des substances gazeuses pures. Cependant, on est souvent amené à étudier des mélanges de gaz. Nous respirons un air qui est composé de 4/5 de diazote (N<sub>2</sub>) et de 1/5 de dioxygène (O<sub>2</sub>). Le diazote est responsable pour 4/5 de la pression atmosphérique que nous subissons et le dioxygène en est responsable pour 1/5. Il en est de même pour la pression dans les pneus de votre vélo.</p>
<p>Dans le cas d’un mélange de gaz, la loi des pressions partielles nous permet de connaître la relation entre la pression totale et la pression partielle de chaque gaz constituant le mélange.</p>
<p>Selon cette loi :</p>
<div class="tcolorbox">
<p>La pression totale d’un mélange de gaz est égale à la somme des pressions partielles de chaque gaz constituant le mélange.</p>
</div>
<p>Soit deux gaz, A et B, contenus dans un volume V. La pression totale <span class="math inline">\(P_T\)</span> est le résultat des collisions des deux types de molécules sur la paroi du contenant. Les collisions entre les molécules de gaz sont négligeables par rapport aux collisions des molécules avec la paroi du contenant. Chaque gaz exerce une pression partielle indépendante en fonction de sa concentration et de sa température dans le mélange.</p>
<p>La loi des gaz parfaits nous permet de connaître la pression exercée par chaque gaz :</p>
<p><span class="math display">\[
\begin{split}
  P_A = \frac{n_A \cdot RT }{V}
\end{split}
\qquad\text{et}\qquad
\begin{split}
  P_B = \frac{n_B \cdot RT }{V}
\end{split}
\]</span></p>
<p>La pression totale d’un mélange de gaz est donnée par la relation suivante :</p>
<p><span class="math display">\[
P_T = P_A + P_B + P_C + ...
\]</span></p>
<p>Dans notre mélange, A et B :</p>
<p><span class="math display">\[
\begin{split}
P_T = P_A + P_B
\end{split}
\qquad\qquad
\begin{split}
  P_T &amp;= \frac{n_A \cdot RT }{V} + \frac{n_B \cdot RT }{V} \\
  &amp;= \frac{RT }{V} \cdot (n_A + n_B)
\end{split}
\]</span></p>
<div class="Exercise">
<p>Un mélange de gaz rares contient 4.46 mol de néon, 0.74 mol d’argon et 2.15 mol de xénon. Calculez les pressions partielles de chaque gaz si la pression totale est de 200 kPa à une température donnée.</p>
</div>
<div class="Answer">
<p><span class="math display">\[
\begin{split}
    \chi_{Ne} &amp;= \frac{n_{Ne}}{n_{Ne}+n_{Ar}+n_{Xe}} = \frac{4.46}{4.46+0.74+2.15} = 0.61 \\
    \chi_{Ar} &amp;= \frac{n_{Ar}}{n_{Ne}+n_{Ar}+n_{Xe}} = \frac{0.74}{4.46+0.74+2.15} = 0.1 \\
    \chi_{Xe} &amp;= \frac{n_{Xe}}{n_{Ne}+n_{Ar}+n_{Xe}} = \frac{2.15}{4.46+0.74+2.15} = 0.29\\
\end{split}
\qquad
\begin{split}
    P_{Ne} &amp;= 0.61 \cdot 200\ \text{ kPa} = 122\ \text{ kPa} \\
    P_{Ar} &amp;= 0.1 \cdot 200\ \text{ kPa} = 20\ \text{ kPa} \\
    P_{Xe} &amp;= 0.29 \cdot 200\ \text{ kPa} = 58\ \text{ kPa} \\
\end{split}
\]</span></p>
</div>
</section>
<section id="résumé" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="résumé"><span class="header-section-number">14.5</span> Résumé</h2>
<ul>
<li>La théorie cinétique décrit un gaz comme un ensemble de particules microscopiques très espacées, en mouvement rectiligne incessant et en collisions élastiques. La pression d’un gaz résulte des collisions de ses particules contre les parois ; leur énergie cinétique moyenne est proportionnelle à la température absolue (en kelvin). Un gaz parfait obéit à toutes ces hypothèses.</li>
<li>Un gaz est caractérisé par quatre variables : le volume <span class="math inline">\(V\)</span>, la température <span class="math inline">\(T\)</span> (en kelvin), la pression <span class="math inline">\(P\)</span> et la quantité de matière <span class="math inline">\(n\)</span>. Les conditions de référence sont les CNTP (273.15 K, <span class="math inline">\(10^5\)</span> Pa) et les CATP (298.15 K, 1 bar).</li>
<li>La pression se mesure en pascals ; équivalences : <span class="math inline">\(1.013\cdot10^5\)</span> Pa = 1 atm = 1.013 bar = 760 mmHg.</li>
<li>Les lois simples relient deux variables. La loi des gaz parfaits <span class="math inline">\(P \cdot V = n \cdot R \cdot T\)</span> relie les quatre variables dans des conditions donnés.</li>
<li>La pression totale d’un mélange gazeux est la somme des pressions partielles de ses constituants ; la pression partielle d’un gaz est proportionnelle à sa fraction molaire.</li>
<li>La loi des gaz parfaits relie un volume gazeux à une quantité de matière : elle intervient dans les calculs stœchiométriques faisant appel à des réactifs ou produits gazeux.</li>
</ul>
</section>
<section id="exercices-supplémentaires" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="exercices-supplémentaires"><span class="header-section-number">14.6</span> Exercices supplémentaires</h2>
<div class="Exercise">
<p>Les pneus d’une voiture ont été gonflés à 1.7 atm à une température de 10° C. Quelle sera la pression de ces pneus à 35° C et à -10° C ?</p>
</div>
<div class="Answer">
<p><span class="math display">\[
\begin{split}
    \text{V et } &amp; \text{n constants}\\
    \frac{P1}{T1} &amp;= \frac{P2}{T2} \\
    \Rightarrow P2 &amp;= \frac{P1 \cdot T2}{T1}
\end{split}
\qquad\qquad
\begin{split}
    P_{35°\ C} &amp;= \frac{1.7\ \text{ atm} \cdot 308.15\ \text{ K}}{283.15\ \text{ K}} = 1.85\ \text{ atm} \\[1em]
    P_{-10°\ C} &amp;= \frac{1.7\ \text{ atm} \cdot 263.15\ \text{ K}}{283.15\ \text{ K}} = 1.58\ \text{ atm}
\end{split}
\]</span></p>
</div>
<div class="Exercise">
<p>Quelle est la masse d’un litre d’ammoniac (NH<sub>3</sub>) aux CNTP ?</p>
</div>
<div class="Answer">
<p><span class="math display">\[
\begin{split}
    P \cdot V &amp;= n \cdot R \cdot T \\
    \Rightarrow n &amp;= \frac{P \cdot V}{R \cdot T}
\end{split}
\qquad
\begin{split}
    n_{\ce{NH3}} &amp;= \frac{1.013 \cdot 10^{5}\ \text{ Pa} \cdot 10^{-3}\ \text{ m}^3}{8.314 \ \mathrm{\frac{J}{mol \cdot K}} \cdot 273.15\ \text{ K}} = 0.045\ \text{ mol} \\[1em]
    m_{\ce{NH3}} &amp;= n_{\ce{NH3}} \cdot M_{\ce{NH3}} = 0.045\ \text{ mol} \cdot 17.034\ \mathrm{\frac{g}{mol}} = 0.767\ \text{ g}
\end{split}
\]</span></p>
</div>
<div class="Exercise">
<p>Un bon vide obtenu dans un appareil de laboratoire correspond à 10<sup>-6</sup> mmHg de pression à 25° C. Calculer le nombre de molécules de gaz par cm<sup>3</sup> dans ces conditions.</p>
</div>
<div class="Answer">
<p><span class="math display">\[
\begin{split}
    P \cdot V &amp;= n \cdot R \cdot T \\
    \Rightarrow n &amp;= \frac{P \cdot V}{R \cdot T}
\end{split}
\]</span></p>
<p><span class="math display">\[
\begin{split}
    P &amp;= 10^{-6}\ \text{ mmHg} = 1.333 \cdot 10^{-4}\ \text{ Pa} \\
    T &amp;= 25°\ C = 298.15\ \text{ K} \\
    V &amp;= 1\ \text{ m}^3 \text{ (arbitrairement)}
\end{split}
\qquad
\begin{split}
    n_{\ce{gaz}} &amp;= \frac{1.333 \cdot 10^{-4}\ \text{ Pa} \cdot 1\ \text{ m}^3}{8.314 \ \mathrm{\frac{J}{mol \cdot K}} \cdot 298.15\ \text{ K}} \\[1em]
    &amp; = 5.378 \cdot 10^{-8}\ \text{ mol}
\end{split}
\]</span></p>
<p><span class="math display">\[
\begin{split}
    \Rightarrow\ &amp; 5.378 \cdot 10^{-8}\ \text{ mol} \text{ de gaz dans 1 $m^3$} \\
    =\ &amp; 3.238 \cdot 10^{16} \text{ \textit{molécules} dans 1 $m^3$} \\
    =\ &amp; 3.238 \cdot 10^{10} \text{ \textit{molécules} dans 1 $cm^3$} \\
    &amp; \text{plus de 32 milliards de molécules dans 1 $cm^3$}
\end{split}
\]</span></p>
</div>
<div class="Exercise">
<p>Près du niveau de la mer, l’air sec a la composition suivante par unité de volume:</p>
<ul>
<li><span class="math inline">\(\ce{N2}\)</span> : 78.08 %</li>
<li><span class="math inline">\(\ce{O2}\)</span> : 20.94 %</li>
<li><span class="math inline">\(\ce{Ar}\)</span> : 0.93 %</li>
<li><span class="math inline">\(\ce{CO2}\)</span> : 0.05 %</li>
</ul>
<p>La pression atmosphérique est de 101.3 kPa. Calculez :</p>
<ol type="a">
<li>La pression partielle de chaque gaz; </li>
<li>La concentration de chaque gaz en moles par litre à 0°C et à pression atmosphérique. </li>
</ol>
</div>
<div class="Answer">
<ol type="a">
<li><span class="math display">\[
\begin{split}
P_{\ce{N2}} &amp;= 0.7808 \cdot 101.3\ \text{ kPa} = 79.1\ \text{ kPa} \\
P_{\ce{O2}} &amp;= 0.2094 \cdot 101.3\ \text{ kPa} = 21.2\ \text{ kPa} \\
P_{\ce{Ar}} &amp;= 0.0093 \cdot 101.3\ \text{ kPa} = 0.94\ \text{ kPa} \\
P_{\ce{CO2}} &amp;= 0.0005 \cdot 101.3\ \text{ kPa} = 0.051\ \text{ kPa}
\end{split}
\]</span></li>
<li>0°C et pression atmosphérique (=CNTP), 1 mole de gaz occupe 22.4 litres.</li>
</ol>
<p><span class="math display">\[
\begin{split}
22.4\ \text{ L/mol} \Rightarrow \frac{1}{22.4}\ \text{ mol/L} = 0.045\ \text{ mol/L}
\end{split}
\]</span></p>
<p><span class="math display">\[
\begin{split}
    C_{\ce{N2}} &amp;= 0.7808 \cdot 0.045\ \text{ mol/L} = 3.5 \cdot 10^{-2}\ \text{ mol/L} \\
    C_{\ce{O2}} &amp;= 0.2094 \cdot 0.045\ \text{ mol/L} = 9 \cdot 10^{-3}\ \text{ mol/L} \\
    C_{\ce{Ar}} &amp;= 0.0093 \cdot 0.045\ \text{ mol/L} = 4 \cdot 10^{-4}\ \text{ mol/L} \\
    C_{\ce{CO2}} &amp;= 0.0005 \cdot 0.045\ \text{ mol/L} = 2.25 \cdot 10^{-5}\ \text{ mol/L}
\end{split}
\]</span></p>
</div>
<div class="Exercise">
<p>Le carbonate de calcium se décompose selon <span class="math inline">\(\ce{CaCO3 -&gt; CaO + CO2}\)</span>. On chauffe 50.0 g de carbonate de calcium. Données : M(CaCO₃) = 100.09 g/mol ; R = 8.314 J·mol<span class="math inline">\(^{-1}\)</span>·K<span class="math inline">\(^{-1}\)</span>.</p>
<ol type="1">
<li>Combien de moles de <span class="math inline">\(\ce{CO2}\)</span> se forment ? </li>
<li>Quel volume ce dioxyde de carbone occupe-t-il à 273.15 K sous une pression de <span class="math inline">\(10^5\)</span> Pa ? </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><span class="math display">\[
n_{\ce{CaCO3}} = \frac{m}{M} = \frac{50.0}{100.09} = 0.500 \text{ mol}
\]</span> La réaction se fait dans le rapport 1:1, donc <span class="math inline">\(n_{\ce{CO2}} = 0.500\)</span> mol.</li>
<li><span class="math display">\[
V = \frac{n \cdot R \cdot T}{P} = \frac{0.500 \cdot 8.314 \cdot 273.15}{10^5} = 0.01135 \text{ m}^3 = 11.35 \text{ l}
\]</span></li>
</ol>
</div>
<div class="Exercise">
<p>Le zinc réagit avec l’acide chlorhydrique selon <span class="math inline">\(\ce{Zn + 2HCl -&gt; ZnCl2 + H2}\)</span>. On fait réagir 6.54 g de zinc. Données : M(Zn) = 65.38 g/mol ; R = 8.314 J·mol<span class="math inline">\(^{-1}\)</span>·K<span class="math inline">\(^{-1}\)</span>.</p>
<p>Quel volume de dihydrogène obtient-on à 25°C (298.15 K) sous une pression de <span class="math inline">\(1.0\cdot10^5\)</span> Pa ?</p>
</div>
<div class="Answer">
<p><span class="math display">\[
n_{\ce{Zn}} = \frac{m}{M} = \frac{6.54}{65.38} = 0.100 \text{ mol}
\]</span> La réaction se fait dans le rapport <span class="math inline">\(\ce{Zn} : \ce{H2} = 1:1\)</span>, donc <span class="math inline">\(n_{\ce{H2}} = 0.100\)</span> mol. <span class="math display">\[
V = \frac{n \cdot R \cdot T}{P} = \frac{0.100 \cdot 8.314 \cdot 298.15}{1.0\cdot10^5} = 2.48\cdot10^{-3} \text{ m}^3 = 2.48 \text{ l}
\]</span></p>
</div>
<div class="Exercise">
<p>La combustion complète du méthane suit <span class="math inline">\(\ce{CH4 + 2O2 -&gt; CO2 + 2H2O}\)</span>. On brûle 16.0 g de méthane. Données : M(CH₄) = 16.04 g/mol ; R = 8.314 J·mol<span class="math inline">\(^{-1}\)</span>·K<span class="math inline">\(^{-1}\)</span>.</p>
<p>Quel volume de dioxygène, mesuré à 25°C (298.15 K) sous <span class="math inline">\(1.0\cdot10^5\)</span> Pa, est nécessaire à cette combustion ?</p>
</div>
<div class="Answer">
<p><span class="math display">\[
n_{\ce{CH4}} = \frac{m}{M} = \frac{16.0}{16.04} = 1.00 \text{ mol}
\]</span> La réaction se fait dans le rapport <span class="math inline">\(\ce{CH4} : \ce{O2} = 1:2\)</span>, donc <span class="math inline">\(n_{\ce{O2}} = 2.00\)</span> mol. <span class="math display">\[
V = \frac{n \cdot R \cdot T}{P} = \frac{2.00 \cdot 8.314 \cdot 298.15}{1.0\cdot10^5} = 4.96\cdot10^{-2} \text{ m}^3 = 49.6 \text{ l}
\]</span></p>
</div>


</section>

</main> <!-- /main -->
<script src="html/vendor/jquery-3.7.1.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {

    var exeContainerClass = 'Exercise-container';
    var exeClass = 'Exercise';
    var ansClass = 'Answer';

    $('.' + exeContainerClass).each(function(i, el) {
      let child = $(el).children('.' + exeClass);
      child.replaceWith(child.html());
      $(el).removeClass(exeContainerClass).addClass(exeClass);
    });

    var chapterNum = $('.quarto-page-breadcrumbs .chapter-number').first().text().trim();

    $('.' + exeClass).each(function(i, el) {
      var num = chapterNum + '.' + (i + 1);
      var title = $('<div>Exercice ' + num + '</div>');
      title.addClass('Label');
      $(el).prepend(title);
    });

    $('.' + ansClass).each(function(i, el) {
      $(el).click(function() {
        $(el).slideToggle();
      });
      var button = $('<button>Solution</button>');
      button.attr('type', 'button');
      button.addClass('Answer-button');
      button.click(function() {
        $(el).slideToggle();
      });
      button.insertBefore(el);
    });

  });
</script>
<script type="text/javascript">
  $(document).ready(function () {
    $("main.content table, main.content .math.display").each(function (i, el) {
      let parent = $("<div>").attr("style", "overflow-x:auto");
      $(el).wrap(parent);
    });
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./130-stoechiometrie.html" class="pagination-link" aria-label="Calculs stœchiométriques">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Calculs stœchiométriques</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./150-cinetique.html" class="pagination-link" aria-label="Cinétique chimique">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cinétique chimique</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>