<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Support du cours de chimie générale | Maturité gymnasiale">

<title>23&nbsp; Thermodynamique – Cours de chimie générale</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./00-references.html" rel="next">
<link href="./220-thermochimie.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-05ad7de8ae34bb1016f06e23b5e9a5a9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script>
window.MathJax = {
  loader: { load: ['[tex]/mhchem', '[tex]/cancel'] },
  tex: { packages: { '[+]': ['mhchem', 'cancel'] } }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./230-thermodynamique.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Thermodynamique</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Cours de chimie générale</a> 
        <div class="sidebar-tools-main">
    <a href="./chimie-generale.pdf" title="Télécharger le PDF" class="quarto-navigation-tool px-1" aria-label="Télécharger le PDF" target="_blank"><i class="bi bi-file-earmark-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Préambule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-etats-de-la-matiere.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Les états de la matière</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-melanges-corps-purs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Mélanges et corps purs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-historique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Historique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./50-atome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">L’atome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./60-tableau-periodique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Le tableau périodique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./70-liaisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Molécules et liaisons chimiques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./80-molecules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Géométrie moléculaire et polarité</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./90-nomenclature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Nomenclature</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./100-solutions-electrolytes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Solutions et électrolytes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./110-reactions-chimiques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Réactions chimiques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./120-types-reactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Types de réactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./130-stoechiometrie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Calculs stœchiométriques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./140-gaz-parfaits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Les gaz parfaits</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./150-cinetique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cinétique chimique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./160-equilibres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">L’équilibre chimique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./170-acides-bases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Les acides et les bases</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./180-ph-potentiel-hydrogene.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Le pH ou potentiel hydrogène</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./190-produit-solubilite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Le produit de solubilité</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./200-oxydoreductions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Les réactions d’oxydoréduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./210-electrochimie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Électrochimie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./220-thermochimie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Thermochimie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./230-thermodynamique.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Thermodynamique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliographie</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#lentropie-s" id="toc-lentropie-s" class="nav-link active" data-scroll-target="#lentropie-s"><span class="header-section-number">23.1</span> L’entropie (S)</a></li>
  <li><a href="#la-deuxième-loi-de-la-thermodynamique" id="toc-la-deuxième-loi-de-la-thermodynamique" class="nav-link" data-scroll-target="#la-deuxième-loi-de-la-thermodynamique"><span class="header-section-number">23.2</span> La deuxième loi de la thermodynamique</a></li>
  <li><a href="#la-troisième-loi-de-la-thermodynamique" id="toc-la-troisième-loi-de-la-thermodynamique" class="nav-link" data-scroll-target="#la-troisième-loi-de-la-thermodynamique"><span class="header-section-number">23.3</span> La troisième loi de la thermodynamique</a></li>
  <li><a href="#la-variation-dentropie-delta-s" id="toc-la-variation-dentropie-delta-s" class="nav-link" data-scroll-target="#la-variation-dentropie-delta-s"><span class="header-section-number">23.4</span> La variation d’entropie (<span class="math inline">\(\Delta S\)</span>)</a>
  <ul class="collapse">
  <li><a href="#lentropie-molaire-standard-so-et-lentropie-de-réaction-delta-so" id="toc-lentropie-molaire-standard-so-et-lentropie-de-réaction-delta-so" class="nav-link" data-scroll-target="#lentropie-molaire-standard-so-et-lentropie-de-réaction-delta-so"><span class="header-section-number">23.4.1</span> L’entropie molaire standard (<span class="math inline">\(S^o\)</span>) et l’entropie de réaction (<span class="math inline">\(\Delta S^o\)</span>)</a></li>
  </ul></li>
  <li><a href="#lénergie-libre-g-et-la-variation-dénergie-libre-delta-g" id="toc-lénergie-libre-g-et-la-variation-dénergie-libre-delta-g" class="nav-link" data-scroll-target="#lénergie-libre-g-et-la-variation-dénergie-libre-delta-g"><span class="header-section-number">23.5</span> L’énergie libre (<span class="math inline">\(G\)</span>) et la variation d’énergie libre (<span class="math inline">\(\Delta G\)</span>)</a></li>
  <li><a href="#lénergie-libre-standard-de-réaction-delta-go" id="toc-lénergie-libre-standard-de-réaction-delta-go" class="nav-link" data-scroll-target="#lénergie-libre-standard-de-réaction-delta-go"><span class="header-section-number">23.6</span> L’énergie libre standard de réaction (<span class="math inline">\(\Delta G^o\)</span>)</a></li>
  <li><a href="#lénergie-libre-et-équilibre-chimique" id="toc-lénergie-libre-et-équilibre-chimique" class="nav-link" data-scroll-target="#lénergie-libre-et-équilibre-chimique"><span class="header-section-number">23.7</span> L’énergie libre et équilibre chimique</a></li>
  <li><a href="#résumé" id="toc-résumé" class="nav-link" data-scroll-target="#résumé"><span class="header-section-number">23.8</span> Résumé</a></li>
  <li><a href="#exercices-supplémentaires" id="toc-exercices-supplémentaires" class="nav-link" data-scroll-target="#exercices-supplémentaires"><span class="header-section-number">23.9</span> Exercices supplémentaires</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Thermodynamique</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="objectives">
<ul>
<li>Définir les notions d’entropie et de variation d’entropie.</li>
<li>Énoncer les deuxième et troisième lois de la thermodynamique.</li>
<li>Calculer l’entropie d’une réaction à partir des entropies standards.</li>
<li>Appliquer la loi de Gibbs pour déterminer la spontanéité d’une réaction.</li>
<li>Appliquer la loi de Gibbs pour effectuer des calculs d’énergie libre standard de réaction.</li>
<li>Décrire comment énergie libre est reliée à l’équilibre chimique.</li>
<li>Interpréter les données thermodynamiques pour prédire les conditions de spontanéité d’une réaction.</li>
<li>Résoudre des problèmes quantitatifs impliquant la variation d’entropie, la spontanéité et la relation à l’équilibre chimique.</li>
</ul>
</div>
<p>La thermodynamique est l’étude de l’énergie et de ses transformations. Dans le chapitre sur la thermochimie, nous nous sommes concentrés sur les transferts de chaleur au cours des réactions chimiques. Nous allons développer d’autres aspects des transferts d’énergie dans ce chapitre.</p>
<p>Nous avons appelé <strong>transformation spontanée</strong>, une transformation qui se produit dans des conditions spécifiques (température, pression et concentration). Une transformation qui ne se produit pas dans des conditions spécifiques est dite <strong>non spontanée</strong>. Nous avons également vu qu’une transformation spontanée dans une direction n’est pas spontanée dans la direction inverse.</p>
<p>Les réactions qui entraînent une diminution de l’énergie d’un système sont souvent spontanées.</p>
<p><span class="math display">\[
\begin{split}
    \ce{CH4(g) + 2O2(g) -&gt; CO2(g) + 2H2O(l)} &amp;\qquad \Delta H^{o} = -890.4 \text{ kJ/mol} \\
    \ce{H^+(aq) + OH^-(aq) -&gt; H2O(l)} &amp;\qquad \Delta H^{o} = -56.2 \text{ kJ/mol}
\end{split}
\]</span></p>
<p>Nous pourrions conclure que les réactions exothermiques ont tendance à être spontanées. Cependant, ça n’est pas toujours le cas. Par exemple, lorsque la glace fond, le processus est endothermique et spontané.</p>
<p><span class="math display">\[
\ce{H2O(s) -&gt; H2O(l)} \qquad \Delta H^{o} = +6.01 \text{ kJ/mol}
\]</span></p>
<p>Cet exemple montre que le signe de <span class="math inline">\(\Delta H\)</span> seul ne permet pas de prédire la spontanéité d’une réaction. la thermodynamique nous permettra de déterminer si une transformation est spontanée ou non pour des conditions données.</p>
<div id="tbl-spontane-non-spontane-exemples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-spontane-non-spontane-exemples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.1: Exemples de transformations spontanées et non spontanées.
</figcaption>
<div aria-describedby="tbl-spontane-non-spontane-exemples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Spontané</th>
<th style="text-align: left;">Non spontané</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">La glace fond à température ambiante.</td>
<td style="text-align: left;">La glace solidifie à température ambiante.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Le sodium métallique réagit avec l’eau pour former de l’hydroxyde de sodium et du dihydrogène.</td>
<td style="text-align: left;">L’hydroxyde de sodium réagit avec l’hydrogène pour produire du sodium métallique et de l’eau.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">La corrosion du fer à température ambiante.</td>
<td style="text-align: left;">La transformation de la rouille en fer métallique à température ambiante.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="lentropie-s" class="level2" data-number="23.1">
<h2 data-number="23.1" class="anchored" data-anchor-id="lentropie-s"><span class="header-section-number">23.1</span> L’entropie (S)</h2>
<div class="tcolorbox">
<p><strong>Entropie - S</strong><br>
Mesure du degré de désordre d’un système. (Exprimée en joules par Kelvin J/K).</p>
</div>
<p><strong>Plus le désordre est grand, plus l’entropie est élevée.</strong></p>
<div class="Exercise">
<p>Classez les états de la matière par ordre d’entropie croissant :</p>
</div>
<div class="Answer">
<p>Les solides sont plus ordonnés que les liquides et les liquides sont moins désordonnés que les gaz.</p>
<p><span class="math display">\[
solides &lt; liquides &lt; gaz
\]</span></p>
</div>
</section>
<section id="la-deuxième-loi-de-la-thermodynamique" class="level2" data-number="23.2">
<h2 data-number="23.2" class="anchored" data-anchor-id="la-deuxième-loi-de-la-thermodynamique"><span class="header-section-number">23.2</span> La deuxième loi de la thermodynamique</h2>
<div class="tcolorbox">
<p><strong>Deuxième loi de la thermodynamique</strong><br>
L’entropie de l’univers entier augmentera toujours avec le temps.</p>
</div>
<p>Supposons que vous construisiez un chateau de cartes. Le processus n’est pas spontané car vous allez dépenser de l’énergie pour bâtir le chateau. Les cartes sont arrangées au dessus de la table, l’énergie potentielle du système est élevée. Les cartes sont disposées dans des positions très spécifiques, le degré de désordre de votre chateau est bas.</p>
<p>Un courant d’air fait voler votre chateau de cartes par terre. Le processus est spontané car les cartes ont pris leurs nouvelles positions toute seules. Les cartes sont disposées à plat sur la table, l’énergie potentielle du système est plus basse. Les cartes sont disposées aléatoirement sur la table, le degré de désordre de votre chateau est élevé.</p>
<div id="fig-cards-castle" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cards-castle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/cards-castle.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cards-castle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23.1: Deuxième loi de la thermodynamique
</figcaption>
</figure>
</div>
<p>Un processus spontané suit donc naturellement deux tendances :</p>
<ul>
<li>Le système évolue spontanément vers un état d’énergie plus faible.</li>
<li>Le système évolue spontanément vers un état plus désordonné.</li>
</ul>
<p>Cela signifie que chaque processus aura tendence à évoluer spontanément vers un plus grand désordre. Le désordre est beaucoup plus probable que l’ordre. Cela s’applique également aux réactions chimiques.</p>
</section>
<section id="la-troisième-loi-de-la-thermodynamique" class="level2" data-number="23.3">
<h2 data-number="23.3" class="anchored" data-anchor-id="la-troisième-loi-de-la-thermodynamique"><span class="header-section-number">23.3</span> La troisième loi de la thermodynamique</h2>
<p>Comme elle est une mesure du désordre, l’entropie doit être nulle dans un système parfaitement régulier et sans désordre. Une substance cristalline au zéro absolu de température, où les mouvements atomique et moléculaire cessent, est considérée d’ordre parfait.</p>
<div class="tcolorbox">
<p><strong>Troisième loi de la thermodynamique</strong><br>
L’entropie d’une substance pure et parfaitement cristalline est nulle à 0 K.</p>
</div>
<p>La troisième loi de la thermodynamique permet de déterminer l’entropie d’une substance à partir de données expérimentales. On transfère lentement de la chaleur à une substance qui se trouve à 0 K et on mesure sa température.</p>
<div id="fig-entropie-graph" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-entropie-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/entropie-graph.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-entropie-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23.2: Entropies du dihydrogène et du chlorométhane en fonction de la température.
</figcaption>
</figure>
</div>
<div class="Exercise">
<p>Répondez aux questions suivantes sur l’entropie.</p>
<ol type="1">
<li>Qu’est-ce que l’entropie d’un système ? Dans quelle unité s’exprime-t-elle ? </li>
<li>Énoncez la deuxième loi de la thermodynamique. </li>
<li>Énoncez la troisième loi de la thermodynamique. Quelle est l’entropie d’un cristal parfait à 0 K ? </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>L’entropie <span class="math inline">\(S\)</span> est une mesure du degré de désordre d’un système : plus le désordre est grand, plus l’entropie est élevée. Elle s’exprime en J/K.</li>
<li>L’entropie de l’univers augmente toujours au cours du temps (tout processus spontané s’accompagne d’une augmentation de l’entropie de l’univers).</li>
<li>L’entropie d’une substance pure et parfaitement cristalline est nulle à 0 K. Un cristal parfait à 0 K a donc une entropie <span class="math inline">\(S = 0\)</span>.</li>
</ol>
</div>
</section>
<section id="la-variation-dentropie-delta-s" class="level2" data-number="23.4">
<h2 data-number="23.4" class="anchored" data-anchor-id="la-variation-dentropie-delta-s"><span class="header-section-number">23.4</span> La variation d’entropie (<span class="math inline">\(\Delta S\)</span>)</h2>
<p>Pour un système qui subit une transfromation entre un état initial et un état final, on peut définir la différence d’entropie entre ces deux états (<span class="math inline">\(\Delta S\)</span>).</p>
<p>En général, l’entropie augmente dans les cas suivants :</p>
<ul>
<li>Une substance est chauffée.</li>
<li>Les solides fondent et deviennent liquides.</li>
<li>Les solides ou les liquides vaporisent pour produire des gaz.</li>
<li>Les solides ou les liquides se dissolvent dans un solvant pour former des solutions.</li>
<li>Une réaction chimique provoque une augmentation du nombre de particules du système.</li>
</ul>
<p>Au cours d’une réaction spontanée, le système devient plus désordonné après qu’avant la réaction, donc <span class="math inline">\(\Delta S &gt; 0\)</span>. La nature “préfère” les valeur de <span class="math inline">\(\Delta S\)</span> positives contrairement aux valeurs <span class="math inline">\(\Delta H\)</span> qui sont généralement négatives (exothermiques).</p>
<div class="Exercise">
<p>Déterminez si l’entropie augmente ou diminue pour les réactions suivantes en justifiant votre réponse :</p>
<ol type="a">
<li><span class="math display">\[ \ce{2 CO(g) + O2(g) -&gt; 2 CO2(g)} \]</span> </li>
<li><span class="math display">\[ \ce{H2O(l) -&gt; H2O(g)} \]</span> </li>
<li><span class="math display">\[ \ce{Na2CO3(s) -&gt; Na2O(s) +CO2(g)} \]</span> </li>
</ol>
</div>
<div class="Answer">
<p>Les solides sont plus ordonnés que les liquides et les liquides sont moins désordonnés que les gaz.</p>
<ol type="a">
<li><span class="math display">\[ \ce{2 CO(g) + O2(g) -&gt; 2 CO2(g)} \quad S \Downarrow \]</span><br>
L’entropie diminue car il y a moins de molécules de gaz de produits et un produit est créé à partir de deux réactifs.</li>
<li><span class="math display">\[ \ce{H2O(l) -&gt; H2O(g)} \quad S \Uparrow \]</span><br>
L’entropie augmente car l’eau subit un changement de phase de liquide à gazeux.</li>
<li><span class="math display">\[ \ce{Na2CO3(s) -&gt; Na2O(s) +CO2(g)} \quad S \Uparrow \]</span><br>
L’entropie augmente car il y a deux molécules du côté des produits dont l’une est un gaz.</li>
</ol>
</div>
<section id="lentropie-molaire-standard-so-et-lentropie-de-réaction-delta-so" class="level3" data-number="23.4.1">
<h3 data-number="23.4.1" class="anchored" data-anchor-id="lentropie-molaire-standard-so-et-lentropie-de-réaction-delta-so"><span class="header-section-number">23.4.1</span> L’entropie molaire standard (<span class="math inline">\(S^o\)</span>) et l’entropie de réaction (<span class="math inline">\(\Delta S^o\)</span>)</h3>
<p>Si l’on considère 4 particules de gaz et 4 moles de particules de gaz, le degré de désordre possible sera plus grand lorsque les particules seront plus nombreuses. La valeur de l’entropie dépend donc de la quantité de matière (propriété extensive). Afin de travailler avec des valeur d’entropie de référence, on introduit l’<strong>entropie molaire standard</strong>.</p>
<div class="tcolorbox">
<p><strong>Entropie molaire standard - <span class="math inline">\(S^o\)</span></strong><br>
L’entropie molaire standard (<span class="math inline">\(S^o\)</span>) est l’entropie de 1 mole d’une substance aux conditions standards.<br>
(Exprimée en joules par mole et par Kelvin J/(mol K)).</p>
</div>
<p>Les entropies molaires standard (<span class="math inline">\(S^{o}\)</span>) servent surtout à calculer les variations d’entropie standard (<span class="math inline">\(\Delta S^{o}\)</span>) des réactions chimiques. On peut relier la variation d’entropie aux entropies des réactifs et des produits de la même manière que pour les enthalpies de formation.</p>
<p><span class="math display">\[
\Delta S^o = \sum n_p \cdot S^{o}(produits) - \sum n_r \cdot S^{o}(reactifs)
\]</span></p>
<p><span class="math inline">\(n_p\)</span> et <span class="math inline">\(n_r\)</span> sont les coéfficients stoechiométriques des réactifs et produits de la réaction étudiée.</p>
<div class="Exercise">
<p>Calculez la variation d’entropie standard (<span class="math inline">\(\Delta S^o\)</span>) de la réaction suivante :</p>
<p><span class="math display">\[ \ce{2 CO(g) + O2(g) -&gt; 2CO2(g)} \]</span></p>
<p>Sachant que :</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Substance</th>
<th style="text-align: center;"><span class="math inline">\(S^o\ \mathrm{J/(mol \cdot K)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\ce{CO2(g)}\)</span></td>
<td style="text-align: center;">213.64</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\ce{CO(g)}\)</span></td>
<td style="text-align: center;">197.91</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\ce{O2(g)}\)</span></td>
<td style="text-align: center;">205.3</td>
</tr>
</tbody>
</table>
<div class="Answer">
<p><span class="math display">\[ \ce{2 CO(g) + O2(g) -&gt; 2CO2(g)} \]</span></p>
<p><span class="math display">\[
\begin{split}
\Delta S^o &amp;= 2\ \text{ mol} \cdot S^o(CO_2) - ( 2\ \text{ mol} \cdot S^o(CO) + S^o(O_2) ) \\
&amp;= 2\ \cancel{\text{mol}} \cdot 213.64 \mathrm{J/(\cancel{mol} \cdot K)} - ( 2\ \cancel{\text{mol}} \cdot 197.91\ \mathrm{J/(\cancel{mol} \cdot K)} + 205.3\ \mathrm{J/(\cancel{mol} \cdot K)} ) \\
&amp;= -173.84\ \text{ J/K}
\end{split}
\]</span></p>
<p>Puisqu’il y a une diminution du nombre de moles d’espèces gazeuses après la réaction, l’entropie diminue. L’entropie des réactifs est supérieure à l’entropie des produits. Par conséquent, le changement d’entropie de la réaction est négatif.</p>
</div>
</section>
</section>
<section id="lénergie-libre-g-et-la-variation-dénergie-libre-delta-g" class="level2" data-number="23.5">
<h2 data-number="23.5" class="anchored" data-anchor-id="lénergie-libre-g-et-la-variation-dénergie-libre-delta-g"><span class="header-section-number">23.5</span> L’énergie libre (<span class="math inline">\(G\)</span>) et la variation d’énergie libre (<span class="math inline">\(\Delta G\)</span>)</h2>
<p>Pour exprimer la spontanéité d’une transformation, nous introduisons une fonction thermodynamique appelée <strong>énergie libre de Gibbs</strong> (G) ou simplement <strong>énergie libre</strong>.</p>
<p>Le travail fourni par une réaction chimique peut changer le volume ou la pression d’un système. L’énergie libre de Gibbs (G) mesure de la quantité d’énergie disponible qui peut être fournie par ce système sans changer ni le volume, ni la pression du système.</p>
<p><span class="math display">\[
G = H - T \cdot S
\]</span></p>
<p>Le travail électrique fourni par une pile électrique en créant une différence de potentiel entre les deux électrodes est un exemple de travail qui ne change pas la pression et le volume du système.</p>
<p>Comme pour les autres grandeurs thermodynamiques, on peut définir une <strong>variation d’énergie libre</strong> (<span class="math inline">\(\Delta G\)</span>). La variation de l’énergie libre d’un système se mesure lorsqu’un système passe d’un état initial à un état final. Dans le cas d’une réaction chimique, lorsque les réactifs se transforment en produits. Cette valeur nous indique l’énergie maximale utilisable libérée (ou absorbée) lors de la réaction.</p>
<p><span class="math display">\[
\Delta G = \Delta H - T \cdot \Delta S
\]</span></p>
<p>En outre, son signe (positif ou négatif) nous indique si une réaction se produira spontanément, c’est-à-dire sans apport d’énergie.</p>
<p>Pour prédire la spontanéité d’une transformation chimique ou physique, il faut connaître à la fois la variation d’enthalpie (<span class="math inline">\(\Delta H\)</span>) mais également la variation d’entropie (<span class="math inline">\(\Delta S\)</span>) associées à la transformation. Pour que cette relation soit vérifiée, deux conditions sont nécessaires :</p>
<ul>
<li>La température reste constante tout au long de la réaction.</li>
<li>La pression reste constante tout au long de la réaction.</li>
</ul>
<p>Cette relation nous permet de prédire la spontanéité d’une réaction lorsqu’on connaît la variation d’enthalpie, la variation d’entropie et la température.</p>
<div id="tbl-spontaneitedHdS" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-spontaneitedHdS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.2: Spontanéité d’une réaction selon le signe de <span class="math inline">\(\Delta G\)</span>.
</figcaption>
<div aria-describedby="tbl-spontaneitedHdS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 41%">
<col style="width: 37%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\Delta G &lt; 0\)</span></td>
<td style="text-align: left;">Réaction <strong>spontanée</strong></td>
<td style="text-align: left;"><strong>Réaction exergonique</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\Delta G &gt; 0\)</span></td>
<td style="text-align: left;">Réaction <strong>non spontanée</strong></td>
<td style="text-align: left;"><strong>Réaction endergonique</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\Delta G = 0\)</span></td>
<td style="text-align: left;">Le système est à l’équilibre</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="Exercise">
<p>La spontanéité d’une réaction (<span class="math inline">\(\Delta G = \Delta H - T \cdot \Delta S\)</span>) dépend des signes de <span class="math inline">\(\Delta H\)</span> et <span class="math inline">\(\Delta S\)</span> ainsi que de la température. Pour chacun des cas suivants, indiquez si la réaction est spontanée à toute température, à aucune température, seulement à basse température ou seulement à haute température.</p>
<ol type="1">
<li><span class="math inline">\(\Delta H &lt; 0\)</span> et <span class="math inline">\(\Delta S &gt; 0\)</span>.</li>
<li><span class="math inline">\(\Delta H &gt; 0\)</span> et <span class="math inline">\(\Delta S &lt; 0\)</span>.</li>
<li><span class="math inline">\(\Delta H &lt; 0\)</span> et <span class="math inline">\(\Delta S &lt; 0\)</span>.</li>
<li><span class="math inline">\(\Delta H &gt; 0\)</span> et <span class="math inline">\(\Delta S &gt; 0\)</span>.</li>
</ol>
</div>
<div class="Answer">
<p>On utilise <span class="math inline">\(\Delta G = \Delta H - T \cdot \Delta S\)</span> ; la réaction est spontanée si <span class="math inline">\(\Delta G &lt; 0\)</span>.</p>
<ol type="1">
<li><span class="math inline">\(\Delta H &lt; 0\)</span> et <span class="math inline">\(-T \cdot \Delta S &lt; 0\)</span> : <span class="math inline">\(\Delta G &lt; 0\)</span> quelle que soit <span class="math inline">\(T\)</span> → spontanée à toute température.</li>
<li><span class="math inline">\(\Delta H &gt; 0\)</span> et <span class="math inline">\(-T \cdot \Delta S &gt; 0\)</span> : <span class="math inline">\(\Delta G &gt; 0\)</span> quelle que soit <span class="math inline">\(T\)</span> → spontanée à aucune température.</li>
<li><span class="math inline">\(\Delta H &lt; 0\)</span> et <span class="math inline">\(-T \cdot \Delta S &gt; 0\)</span> : <span class="math inline">\(\Delta G &lt; 0\)</span> seulement si <span class="math inline">\(T\)</span> est faible → spontanée à basse température.</li>
<li><span class="math inline">\(\Delta H &gt; 0\)</span> et <span class="math inline">\(-T \cdot \Delta S &lt; 0\)</span> : <span class="math inline">\(\Delta G &lt; 0\)</span> seulement si <span class="math inline">\(T\)</span> est grand → spontanée à haute température.</li>
</ol>
</div>
</section>
<section id="lénergie-libre-standard-de-réaction-delta-go" class="level2" data-number="23.6">
<h2 data-number="23.6" class="anchored" data-anchor-id="lénergie-libre-standard-de-réaction-delta-go"><span class="header-section-number">23.6</span> L’énergie libre standard de réaction (<span class="math inline">\(\Delta G^o\)</span>)</h2>
<p>Tout comme pour l’enthalpie et l’entropie, afin de travailler avec des valeur de référence, on introduit l’<strong>énergie libre standard de réaction</strong>. L’énergie libre standard de réaction (<span class="math inline">\(\Delta G^o\)</span>) est la variation d’énergie libre pour une réaction lorsqu’elle se produit dans les conditions standard, c’est-à-dire lorsque des réactifs dans leur état standard sont convertis en produits dans leur état standard. La relation précédente devient :</p>
<p><span class="math display">\[
\Delta G^o = \Delta H^o - T \cdot \Delta S^o
\]</span></p>
<div class="Exercise">
<p>Utilisez l’équation de Gibbs pour déterminer la variation d’énergie libre standard, à 25°C, des réactions suivantes.</p>
<ol type="a">
<li><span class="math display">\[
\begin{split}
&amp; \ce{2 NO(g) + O2(g) -&gt; 2 NO2(g)} \\
&amp; \Delta H^o = -114.1 \text{ kJ} \text{ et } \Delta S^o = -146.2 \text{ J/K}
\end{split}
\]</span> </li>
<li><span class="math display">\[
\begin{split}
&amp; \ce{2 CO(g) + 2 NH3(g) -&gt; C2H6(g) + 2 NO(g)} \\
&amp; \Delta H^o = 409 \text{ kJ} \text{ et } \Delta S^o = -129.1 \text{ J/K}
\end{split}
\]</span> </li>
</ol>
</div>
<div class="Answer">
<ol type="a">
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta H^o - T \cdot \Delta S^o \\
&amp;= -114.1\ \text{ kJ} - 298.15 \cdot (-0.1462\ \text{ kJ/K}) \\
&amp;= -70.5\ \text{ kJ} \quad \text{(Réaction spontanée)}
\end{split}
\]</span></li>
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta H^o - T \cdot \Delta S^o \\
&amp;= 409\ \text{ kJ} - 298.15 \cdot (-0.1291\ \text{ kJ/K}) \\
&amp;= 447.5\ \text{ kJ} \quad \text{(Réaction non spontanée)}
\end{split}
\]</span></li>
</ol>
</div>
<p>Les énergies libres standard de formation (<span class="math inline">\(\Delta G^o_f\)</span>) sont des valeurs que l’on peut trouver dans des tables et qui permettent de calculer l’énergie libre standard d’une réaction en utilisant la relation suivante :</p>
<p><span class="math display">\[
\Delta G^o = \sum n_p \cdot \Delta G^{o}_f(produits) - \sum n_r \cdot \Delta G^{o}_f(reactifs)
\]</span></p>
<div class="Exercise">
<p>Calculez <span class="math inline">\(\Delta G^o\)</span> à 298 K de la réaction suivante :</p>
<p><span class="math display">\[ \ce{4 HCl(g) + O2(g) -&gt; 2 Cl2(g) + 2 H2O(g)} \]</span></p>
<ol type="a">
<li>En utilisant l’équation de Gibbs : <span class="math display">\[
\Delta S^o = -128.8\ \text{ J/K} \qquad \Delta H^o = -114.4\ \text{ kJ}
\]</span> </li>
<li>En utilisant les énergies libres standard de formation : <span class="math display">\[
\begin{split}
&amp; \Delta G^o_f(\ce{HCl(g)}) = -95.3\ \text{ kJ/mol} \quad \Delta G^o_f(\ce{O2(g)}) = 0\ \text{ kJ/mol} \\
&amp; \Delta G^o_f(\ce{Cl2(g)}) = 0\ \text{ kJ/mol} \quad \Delta G^o_f(\ce{H2O(g)}) = -228.6\ \text{ kJ/mol}
\end{split}
\]</span> </li>
</ol>
</div>
<div class="Answer">
<ol type="a">
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta H^o - T \cdot \Delta S^o \\
&amp;= -114.4\ \text{ kJ} - 298\ \text{ K} \cdot (-0.1288)\ \text{ kJ/K} \\
&amp;= -114.4\ \text{ kJ} + 38.4\ \text{ kJ} = -76\ \text{ kJ}
\end{split}
\]</span></li>
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= [2 \Delta G^o_f(\ce{Cl2(g)}) + 2 \Delta G^o_f(\ce{H2O(g)})] - [4 \Delta G^o_f(\ce{HCl(g)}) + \Delta G^o_f(\ce{O2(g)})] \\
&amp;= [2 \cdot 0\ \text{ kJ/mol} + 2 \cdot (-228.6)\ \text{ kJ/mol}] - [4 \cdot (-95.3)\ \text{ kJ/mol} + 1 \cdot 0\ \text{ kJ/mol}] \\
&amp;= (-457.2 + 381.2) \text{ kJ} = -76\ \text{ kJ}
\end{split}
\]</span></li>
</ol>
</div>
</section>
<section id="lénergie-libre-et-équilibre-chimique" class="level2" data-number="23.7">
<h2 data-number="23.7" class="anchored" data-anchor-id="lénergie-libre-et-équilibre-chimique"><span class="header-section-number">23.7</span> L’énergie libre et équilibre chimique</h2>
<p>Les réactifs et les produits d’une réaction sont presque toujours dans un état différent de leur état standard. Pour déterminer si une réaction est spontanée, il faut donc tenir compte des concentrations et/ou des pressions des espèces impliquées. Il est possible de connaître <span class="math inline">\(\Delta G^o\)</span> à partir de tables, mais il faut connaître <span class="math inline">\(\Delta G\)</span> pour déterminer la spontanéité.</p>
<p>La thermodynamique nous apprend que la relation entre <span class="math inline">\(\Delta G\)</span> et <span class="math inline">\(\Delta G^o\)</span> est la suivante :</p>
<p><span class="math display">\[
\Delta G = \Delta G^o + RT \cdot ln(Q)
\]</span></p>
<p>où <span class="math inline">\(R\)</span> est la constante des gaz parfaits, T est la température en kelvin et Q est le quotient de réaction.</p>
<p>Par définition, à l’équilibre, <span class="math inline">\(\Delta G = 0\)</span> et <span class="math inline">\(Q = K\)</span> (K est la constante d’équilibre). Ainsi :</p>
<p><span class="math display">\[
0 = \Delta G^o + RT \cdot ln(K) \quad \Rightarrow \quad \Delta G^o = - RT \cdot ln(K)
\]</span></p>
<div id="tbl-spontaneiteDGK" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-spontaneiteDGK-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.3: Relation entre constante d’équilibre (K) et énergie libre standard de réaction (<span class="math inline">\(\Delta G^o\)</span>).
</figcaption>
<div aria-describedby="tbl-spontaneiteDGK-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(K\)</span></th>
<th style="text-align: center;"><span class="math inline">\(ln(K)\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\Delta G^o\)</span></th>
<th style="text-align: left;">Résultat à l’équilibre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">&gt; 1</td>
<td style="text-align: center;">positif</td>
<td style="text-align: center;">négatif</td>
<td style="text-align: left;">Les produits sont favorisés</td>
</tr>
<tr class="even">
<td style="text-align: center;">= 1</td>
<td style="text-align: center;">nul</td>
<td style="text-align: center;">nul</td>
<td style="text-align: left;">Ni produits, ni réactifs sont favorisés</td>
</tr>
<tr class="odd">
<td style="text-align: center;">&lt; 1</td>
<td style="text-align: center;">négatif</td>
<td style="text-align: center;">positif</td>
<td style="text-align: left;">Les réactifs sont favorisés</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Selon cette équation, plus K est grand, plus <span class="math inline">\(\Delta G^o\)</span> est négatif. Cette équation permet de déterminer la constante d’équilibre d’une réaction si l’on connaît la variation de l’énergie libre standard, et vice versa.</p>
<div id="fig-dG-profile" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dG-profile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/dG-profile.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dG-profile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23.3: Énergie libre standard et transformation spontanée
</figcaption>
</figure>
</div>
<div class="Exercise">
<p>Déterminez la valeur de la constante d’équilibre, à 25°C, de la réaction suivante :</p>
<p><span class="math display">\[
\ce{2 NO2(g) &lt;=&gt; N2O4(g)}
\]</span></p>
<p>Avec <span class="math display">\[
\begin{split}
\Delta G^o_f[\ce{N2O4(g)}] = 97.82\ \text{ kJ/mol}
\end{split}
\qquad
\begin{split}
\Delta G^o_f[\ce{NO2(g)}] = 51.30\ \text{ kJ/mol}
\end{split}
\]</span></p>
</div>
<div class="Answer">
<p><span class="math display">\[
\ce{2 NO2(g) &lt;=&gt; N2O4(g)}
\]</span></p>
<p><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta G^o_f[\ce{N2O4(g)}] - 2 \cdot \Delta G^o_f[\ce{NO2(g)}] \\
&amp;= 97.82\ \mathrm{\frac{kJ}{mol}} - 2 \cdot 51.30\ \mathrm{\frac{kJ}{mol}} \\
&amp;= -4.78\ \text{ kJ/mol}
\end{split}
\]</span></p>
<p><span class="math display">\[
\begin{split}
\Delta G^o &amp;= - RT \cdot ln(K) \\
ln(K) &amp;= \frac{- \Delta G^o}{RT} = \frac{- (-4780\ \text{ J/mol})}{8.314\ \mathrm{J/(mol \cdot K)} \cdot 298.15\ \text{ K}} = 1.93 \\
K &amp;= e^{1.93} = 6.9
\end{split}
\]</span></p>
</div>
</section>
<section id="résumé" class="level2" data-number="23.8">
<h2 data-number="23.8" class="anchored" data-anchor-id="résumé"><span class="header-section-number">23.8</span> Résumé</h2>
<ul>
<li>L’entropie <span class="math inline">\(S\)</span> mesure le degré de désordre d’un système (en J/K) : plus le désordre est grand, plus <span class="math inline">\(S\)</span> est élevée.</li>
<li>L’entropie de l’univers augmente toujours et l’entropie d’une substance pure parfaitement cristalline est nulle à 0 K.</li>
<li>La variation d’entropie standard d’une réaction se calcule à partir des entropies molaires standard.</li>
<li>L’énergie libre de Gibbs <span class="math inline">\(G = H - T \cdot S\)</span> ; sa variation vaut <span class="math inline">\(\Delta G = \Delta H - T \cdot \Delta S\)</span> (à <span class="math inline">\(T\)</span> et <span class="math inline">\(P\)</span> constantes). Le signe de <span class="math inline">\(\Delta G\)</span> donne la spontanéité : <span class="math inline">\(\Delta G &lt; 0\)</span> réaction spontanée (exergonique) ; <span class="math inline">\(\Delta G &gt; 0\)</span> non spontanée (endergonique) ; <span class="math inline">\(\Delta G = 0\)</span> équilibre.</li>
<li>Selon les signes de <span class="math inline">\(\Delta H\)</span> et <span class="math inline">\(\Delta S\)</span>, une réaction peut être spontanée à toute température, à aucune, seulement à basse ou seulement à haute température.</li>
<li>L’énergie libre standard de réaction se calcule aussi à partir des énergies libres standard de formation.</li>
<li>Hors des conditions standard : <span class="math inline">\(\Delta G = \Delta G^o + RT \cdot \ln Q\)</span>. À l’équilibre <span class="math inline">\(\Delta G = 0\)</span> et <span class="math inline">\(Q = K\)</span>, d’où <span class="math inline">\(\Delta G^o = -RT \cdot \ln K\)</span> : un <span class="math inline">\(\Delta G^o\)</span> négatif correspond à <span class="math inline">\(K &gt; 1\)</span> (produits favorisés).</li>
</ul>
</section>
<section id="exercices-supplémentaires" class="level2" data-number="23.9">
<h2 data-number="23.9" class="anchored" data-anchor-id="exercices-supplémentaires"><span class="header-section-number">23.9</span> Exercices supplémentaires</h2>
<div class="Exercise">
<p>Dans chacun des cas suivants, prédisez s’il y aura une augmentation ou une diminution de l’entropie du système. Si vous ne pouvez pas prédire, expliquez pourquoi.</p>
<ol type="a">
<li>La synthèse de l’ammoniac.<br>
<span class="math display">\[ \ce{N2(g) + 3 H2(g) -&gt; 2 NH3(g)} \]</span></li>
<li>La préparation d’une solution de saccharose (sucre de table).<br>
<span class="math display">\[ \ce{C12H22O11(s) + H2O(l) -&gt; C12H22O11(aq)} \]</span></li>
<li>L’évaporation à sec d’une solution aqueuse d’urée. <span class="math display">\[ \ce{CO(NH2)2(aq) -&gt; CO(NH2)2(s)} \]</span></li>
</ol>
</div>
<div class="Answer">
<ol type="a">
<li>Quatre moles de réactifs gazeux donnent deux moles de produits gazeux. Deux moles de gaz sont perdues.<br>
<span class="math display">\[ S \Downarrow, \text{l'entropie diminue} \]</span></li>
<li>Les molécules de saccharose sont très ordonnées à l’état solide. Elles sont distribuées au hasard dans la solution aqueuse.<br>
<span class="math display">\[ S \Uparrow, \text{l'entropie augmente} \]</span></li>
<li>L’eau s’évapore et se convertit en gaz. <span class="math inline">\(S \Uparrow\)</span> (l’entropie augmente). L’urée passe d’une distribution aléatoire dans la solution à un solide très ordonné. <span class="math inline">\(S \Downarrow\)</span> (l’entropie diminue). Sans autre information, on ne peut pas dire si l’entropie du système augmente ou diminue.</li>
</ol>
</div>
<div class="Exercise">
<p>Calculez la variation d’entropie standard (<span class="math inline">\(\Delta S^o\)</span>) de la réaction suivante :</p>
<p><span class="math display">\[ \ce{4 HCl(g) + O2(g) -&gt; 2 Cl2(g) + 2 H2O(g)} \]</span></p>
</div>
<p>Sachant que :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Substance</th>
<th style="text-align: center;"><span class="math inline">\(S^o\ \mathrm{J/(mol \cdot K)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\ce{HCl(g)}\)</span></td>
<td style="text-align: center;">186.8</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\ce{O2(g)}\)</span></td>
<td style="text-align: center;">205.0</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\ce{Cl2(g)}\)</span></td>
<td style="text-align: center;">223.0</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\ce{H2O(g)}\)</span></td>
<td style="text-align: center;">188.7</td>
</tr>
</tbody>
</table>
<div class="Answer">
<p><span class="math display">\[ \ce{4 HCl(g) + O2(g) -&gt; 2 Cl2(g) + 2 H2O(g)} \]</span></p>
<p><span class="math display">\[
\begin{split}
\Delta S^o &amp;= (2\ \text{ mol} \cdot S^o(Cl_2) + 2\ \text{ mol} \cdot S^o(H_2O) ) - ( 4\ \text{ mol} \cdot S^o(HCl) + S^o(O_2) ) \\
&amp;= (2\ \text{ mol} \cdot 223.0\ \mathrm{J/(mol \cdot K)} + 2\ \text{ mol} \cdot 188.7\ \mathrm{J/(mol \cdot K)} ) \\
&amp; \qquad - ( 4\ \text{ mol} \cdot 186.8\ \mathrm{J/(mol \cdot K)} + 205.0\ \mathrm{J/(mol \cdot K)} ) \\
&amp;= -128.8\ \text{ J/K}
\end{split}
\]</span></p>
<p><span class="math inline">\(\Delta S^o\)</span> est négatif, l’entropie diminue.</p>
</div>
<div class="Exercise">
<p>L’oxyde de calcium (<span class="math inline">\(\ce{CaO}\)</span>), également appelé chaux vive, est une substance qui est utilisée dans de nombreuses applications industrielles. On peut le préparer par décomposition à haute températureen du calcaire (<span class="math inline">\(\ce{CaCO3}\)</span>), selon l’équation :</p>
<p><span class="math display">\[ \ce{CaCO3(s) &lt;=&gt; CaO(s) + CO2(g)} \]</span></p>
<p>La réaction est réversible et, sous certaines conditions, le <span class="math inline">\(\ce{CaO}\)</span> et le <span class="math inline">\(\ce{CO2}\)</span> se recombinent pour former à nouveau du <span class="math inline">\(\ce{CaCO3}\)</span>. Pour éviter que cela ne se produise, le <span class="math inline">\(\ce{CO2}\)</span> est éliminé à mesure qu’il se forme, favorisant la réaction directe.</p>
<p>Vous allez estimez la température à laquelle cet équilibre commence à favoriser les produits pour maximiser la production de <span class="math inline">\(\ce{CaO}\)</span>. (<a href="https://bit.ly/GNLC-TPTS"><strong>Table des propriétés thermodynamiques standard</strong></a>)</p>
<ol type="1">
<li>Calculez la variation d’enthalpie standard de la réaction : </li>
<li>Calculez la variation d’entropie standard de la réaction : </li>
<li>À l’aide de la relation de Gibbs, calculez l’énergie libre standard de la réaction : </li>
<li>Aux conditions standards, la réaction favorise-t-elle les produits ou les réactifs ? (Justifiez votre réponse). </li>
<li>Calculez à quelle température la réaction atteint un équilibre entre produits et réactifs. </li>
<li>Calculez l’énergie libre de la réaction à une température de 5° supérieure à cette température. </li>
<li>Dans ces conditions, la réaction favorise-t-elle les produits ou les réactifs ? (Justifiez votre réponse). </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><span class="math display">\[
\begin{split}
\ce{\Delta H^o &amp;= [\Delta H^o_f(\ce{CaO}) + \Delta H^o_f(\ce{CO2})] - [\Delta H^o_f(\ce{CaCO3})]} \\
&amp;= [(-634.9\ \text{ kJ/mol}) + (-393.51\ \text{ kJ/mol})] - (-1220.0\ \text{ kJ/mol}) \\
&amp;= 191.59\ \text{ kJ/mol}
\end{split}
\]</span></li>
<li><span class="math display">\[
\begin{split}
\ce{\Delta S^o &amp;= [S^o_f(\ce{CaO}) + S^o_f(\ce{CO2})] - [S^o_f(\ce{CaCO3})]} \\
&amp;= (38.1\ \mathrm{J/(K \cdot mol)} + 213.8\ \mathrm{J/(K \cdot mol)}) - (110.0\ \mathrm{J/(K \cdot mol)}) \\
&amp;= 141.9\ \mathrm{J/(K \cdot mol)} = 0.1419\ \mathrm{kJ/(K \cdot mol)}
\end{split}
\]</span></li>
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta H^o - T \cdot \Delta S^o \\
&amp;= 191.59\ \text{ kJ/mol} - (298\ \text{ K} \cdot 0.1419\ \mathrm{kJ/(K \cdot mol)} ) \\
&amp;= 149.3\ \text{ kJ/mol}
\end{split}
\]</span></li>
<li>Aux conditions standards, la réaction favorise les réactifs car l’énergie libre standard est supérieure à zéro.</li>
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta H^o - T \cdot \Delta S^o \\
\text{à l'équilibre } \Delta G^o &amp;= 0 \\
\Rightarrow 0 &amp;= \Delta H^o - T \cdot \Delta S^o \\
\end{split}
\qquad
\begin{split}
T &amp;= \frac{\Delta H^o}{\Delta S^o} \\
&amp;= \frac{191.59\ \text{ kJ/mol}}{0.1419\ \mathrm{kJ/(K \cdot mol)}} \\
&amp;= 1350\ \text{ K} \quad (1077\ \text{ °C})
\end{split}
\]</span></li>
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta H^o - T \cdot \Delta S^o \\
&amp;= 191.59\ \text{ kJ/mol} - (1355\ \text{ K} \cdot 0.1419\ \mathrm{kJ/(K \cdot mol)} ) \\
&amp;= -0.68\ \text{ kJ/mol}
\end{split}
\]</span></li>
<li>Dans ces conditions, la réaction favorise les produits car l’énergie libre standard est inférieure à zéro.</li>
</ol>
<p>Dans cet exemple, les valeurs standards de <span class="math inline">\(\Delta H^o\)</span> et <span class="math inline">\(\Delta S^o\)</span> sont utilisées pour calculer le <span class="math inline">\(\Delta G^o\)</span> à des températures beaucoup plus élevées. Cette approche ne nous donne pas une valeur précise pour <span class="math inline">\(\Delta G^o\)</span> car <span class="math inline">\(\Delta H^o\)</span> et <span class="math inline">\(\Delta S^o\)</span> changent avec la température, mais c’est une estimation raisonnablement convenable.</p>
</div>
<div class="Exercise">
<p>Pour la synthèse de l’ammoniac <span class="math inline">\(\ce{N2(g) + 3 H2(g) -&gt; 2 NH3(g)}\)</span> à 298 K, on donne <span class="math inline">\(\Delta H^o = -92.2\)</span> kJ et <span class="math inline">\(\Delta S^o = -198.8\)</span> J/K.</p>
<ol type="1">
<li>Calculez <span class="math inline">\(\Delta G^o\)</span> à 298 K. La réaction est-elle spontanée dans les conditions standard ? </li>
<li>Calculez la constante d’équilibre <span class="math inline">\(K\)</span> à 298 K. </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><span class="math display">\[
\begin{split}
\Delta G^o &amp;= \Delta H^o - T \cdot \Delta S^o \\
&amp;= -92.2 - 298 \cdot (-0.1988) = -92.2 + 59.2 = -33.0 \text{ kJ}
\end{split}
\]</span> <span class="math inline">\(\Delta G^o &lt; 0\)</span> : la réaction est spontanée dans les conditions standard.</li>
<li><span class="math inline">\(\Delta G^o = -RT \cdot \ln K\)</span>, donc : <span class="math display">\[
\ln K = \frac{-\Delta G^o}{RT} = \frac{33000}{8.314 \cdot 298} = 13.3 \qquad K = e^{13.3} = 6.0 \cdot 10^{5}
\]</span></li>
</ol>
</div>


</section>

</main> <!-- /main -->
<script src="html/vendor/jquery-3.7.1.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {

    var exeContainerClass = 'Exercise-container';
    var exeClass = 'Exercise';
    var ansClass = 'Answer';

    $('.' + exeContainerClass).each(function(i, el) {
      let child = $(el).children('.' + exeClass);
      child.replaceWith(child.html());
      $(el).removeClass(exeContainerClass).addClass(exeClass);
    });

    var chapterNum = $('.quarto-page-breadcrumbs .chapter-number').first().text().trim();

    $('.' + exeClass).each(function(i, el) {
      var num = chapterNum + '.' + (i + 1);
      var title = $('<div>Exercice ' + num + '</div>');
      title.addClass('Label');
      $(el).prepend(title);
    });

    $('.' + ansClass).each(function(i, el) {
      $(el).click(function() {
        $(el).slideToggle();
      });
      var button = $('<button>Solution</button>');
      button.attr('type', 'button');
      button.addClass('Answer-button');
      button.click(function() {
        $(el).slideToggle();
      });
      button.insertBefore(el);
    });

  });
</script>
<script type="text/javascript">
  $(document).ready(function () {
    $("main.content table, main.content .math.display").each(function (i, el) {
      let parent = $("<div>").attr("style", "overflow-x:auto");
      $(el).wrap(parent);
    });
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./220-thermochimie.html" class="pagination-link" aria-label="Thermochimie">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Thermochimie</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./00-references.html" class="pagination-link" aria-label="Bibliographie">
        <span class="nav-page-text">Bibliographie</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>