<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Support du cours de chimie générale | Maturité gymnasiale">

<title>6&nbsp; Le tableau périodique – Cours de chimie générale</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./70-liaisons.html" rel="next">
<link href="./50-atome.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-05ad7de8ae34bb1016f06e23b5e9a5a9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script>
window.MathJax = {
  loader: { load: ['[tex]/mhchem', '[tex]/cancel'] },
  tex: { packages: { '[+]': ['mhchem', 'cancel'] } }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./60-tableau-periodique.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Le tableau périodique</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Cours de chimie générale</a> 
        <div class="sidebar-tools-main">
    <a href="./chimie-generale.pdf" title="Télécharger le PDF" class="quarto-navigation-tool px-1" aria-label="Télécharger le PDF" target="_blank"><i class="bi bi-file-earmark-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Préambule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-etats-de-la-matiere.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Les états de la matière</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-melanges-corps-purs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Mélanges et corps purs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-historique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Historique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./50-atome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">L’atome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./60-tableau-periodique.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Le tableau périodique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./70-liaisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Molécules et liaisons chimiques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./80-molecules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Géométrie moléculaire et polarité</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./90-nomenclature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Nomenclature</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./100-solutions-electrolytes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Solutions et électrolytes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./110-reactions-chimiques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Réactions chimiques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./120-types-reactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Types de réactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./130-stoechiometrie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Calculs stœchiométriques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./140-gaz-parfaits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Les gaz parfaits</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./150-cinetique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cinétique chimique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./160-equilibres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">L’équilibre chimique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./170-acides-bases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Les acides et les bases</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./180-ph-potentiel-hydrogene.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Le pH ou potentiel hydrogène</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./190-produit-solubilite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Le produit de solubilité</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./200-oxydoreductions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Les réactions d’oxydoréduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./210-electrochimie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Électrochimie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./220-thermochimie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Thermochimie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./230-thermodynamique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Thermodynamique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliographie</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#la-classification-périodique" id="toc-la-classification-périodique" class="nav-link active" data-scroll-target="#la-classification-périodique"><span class="header-section-number">6.1</span> La classification périodique</a>
  <ul class="collapse">
  <li><a href="#métaux-non-métaux-métalloïdes" id="toc-métaux-non-métaux-métalloïdes" class="nav-link" data-scroll-target="#métaux-non-métaux-métalloïdes"><span class="header-section-number">6.1.1</span> Métaux, non-métaux, métalloïdes</a></li>
  <li><a href="#les-périodes" id="toc-les-périodes" class="nav-link" data-scroll-target="#les-périodes"><span class="header-section-number">6.1.2</span> Les périodes</a></li>
  <li><a href="#les-familles" id="toc-les-familles" class="nav-link" data-scroll-target="#les-familles"><span class="header-section-number">6.1.3</span> Les familles</a></li>
  </ul></li>
  <li><a href="#interactions-rayonnement-matière" id="toc-interactions-rayonnement-matière" class="nav-link" data-scroll-target="#interactions-rayonnement-matière"><span class="header-section-number">6.2</span> Interactions rayonnement-matière</a>
  <ul class="collapse">
  <li><a href="#les-ondes-électromagnétiques" id="toc-les-ondes-électromagnétiques" class="nav-link" data-scroll-target="#les-ondes-électromagnétiques"><span class="header-section-number">6.2.1</span> Les ondes électromagnétiques</a></li>
  <li><a href="#longueur-donde-fréquence-et-énergie" id="toc-longueur-donde-fréquence-et-énergie" class="nav-link" data-scroll-target="#longueur-donde-fréquence-et-énergie"><span class="header-section-number">6.2.2</span> Longueur d’onde, fréquence et énergie</a></li>
  <li><a href="#le-spectre-électromagnétique" id="toc-le-spectre-électromagnétique" class="nav-link" data-scroll-target="#le-spectre-électromagnétique"><span class="header-section-number">6.2.3</span> Le spectre électromagnétique</a></li>
  <li><a href="#interactions-rayonnement-matière-1" id="toc-interactions-rayonnement-matière-1" class="nav-link" data-scroll-target="#interactions-rayonnement-matière-1"><span class="header-section-number">6.2.4</span> Interactions rayonnement-matière</a></li>
  </ul></li>
  <li><a href="#les-orbitales-atomiques" id="toc-les-orbitales-atomiques" class="nav-link" data-scroll-target="#les-orbitales-atomiques"><span class="header-section-number">6.3</span> Les orbitales atomiques</a>
  <ul class="collapse">
  <li><a href="#la-configuration-électronique" id="toc-la-configuration-électronique" class="nav-link" data-scroll-target="#la-configuration-électronique"><span class="header-section-number">6.3.1</span> La configuration électronique</a></li>
  <li><a href="#déterminer-une-configuration-électronique" id="toc-déterminer-une-configuration-électronique" class="nav-link" data-scroll-target="#déterminer-une-configuration-électronique"><span class="header-section-number">6.3.2</span> Déterminer une configuration électronique</a></li>
  </ul></li>
  <li><a href="#les-électrons-de-valence" id="toc-les-électrons-de-valence" class="nav-link" data-scroll-target="#les-électrons-de-valence"><span class="header-section-number">6.4</span> Les électrons de valence</a></li>
  <li><a href="#la-règle-de-loctet" id="toc-la-règle-de-loctet" class="nav-link" data-scroll-target="#la-règle-de-loctet"><span class="header-section-number">6.5</span> La règle de l’octet</a></li>
  <li><a href="#les-ions" id="toc-les-ions" class="nav-link" data-scroll-target="#les-ions"><span class="header-section-number">6.6</span> Les ions</a>
  <ul class="collapse">
  <li><a href="#le-cation-ou-la-perte-délectrons" id="toc-le-cation-ou-la-perte-délectrons" class="nav-link" data-scroll-target="#le-cation-ou-la-perte-délectrons"><span class="header-section-number">6.6.1</span> Le cation ou la perte d’électrons</a></li>
  <li><a href="#lanion-ou-le-gain-délectrons" id="toc-lanion-ou-le-gain-délectrons" class="nav-link" data-scroll-target="#lanion-ou-le-gain-délectrons"><span class="header-section-number">6.6.2</span> L’anion ou le gain d’électrons</a></li>
  <li><a href="#les-ions-stables---groupe-a" id="toc-les-ions-stables---groupe-a" class="nav-link" data-scroll-target="#les-ions-stables---groupe-a"><span class="header-section-number">6.6.3</span> Les ions stables - groupe A</a></li>
  <li><a href="#les-ions-des-éléments-de-transition---groupe-b" id="toc-les-ions-des-éléments-de-transition---groupe-b" class="nav-link" data-scroll-target="#les-ions-des-éléments-de-transition---groupe-b"><span class="header-section-number">6.6.4</span> Les ions des éléments de transition - groupe B</a></li>
  </ul></li>
  <li><a href="#résumé" id="toc-résumé" class="nav-link" data-scroll-target="#résumé"><span class="header-section-number">6.7</span> Résumé</a></li>
  <li><a href="#exercices-supplémentaires" id="toc-exercices-supplémentaires" class="nav-link" data-scroll-target="#exercices-supplémentaires"><span class="header-section-number">6.8</span> Exercices supplémentaires</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Le tableau périodique</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="objectives">
<ul>
<li>Décrire comment les éléments sont organisés dans le tableau périodique donnant lieu à des périodes, des familles et des groupes.</li>
<li>Décrire les caractéristiques ondulatoires de la lumière (fréquence, la longueur d’onde et énergie) et les régions générales du spectre électromagnétique.</li>
<li>Décrire la relation entre la longueur d’onde, la fréquence et l’énergie d’une onde électromagnétique.</li>
<li>Décrire comment la matière interagit avec les rayonnements électromagnétiques et mène aux spectres d’absorption et d’émission.</li>
<li>Repérer les éléments sur le tableau périodique et les classer en métaux, non-métaux ou métalloïdes.</li>
<li>Décrire la répartition des électrons en couches, sous-couches et orbitales autour du noyau atomique.</li>
<li>Prédire les configurations électroniques complète et simplifiée d’un élément grâce au tableau périodique.</li>
<li>Identifier les électrons de valence d’un atome et leurs correspondance avec les différents groupes du tableau périodique.</li>
<li>Représenter la structure de Lewis d’un atome donné.</li>
<li>Définir les termes ions, cations et anions.</li>
<li>Utiliser la règle de l’octet pour prédire l’ion stable que formera un élément du bloc principal.</li>
</ul>
</div>
<p>A la fin du 18ème siècle, Lavoisier a compilé une liste des 23 éléments connus à l’époque. En 1870, on en connaissait 65, et 88 en 1925. Aujourd’hui, on en dénombre 118.</p>
<p>Les chimistes ont regroupé les éléments de sorte à ce qu’ils n’aient pas à mémoriser individuellement les propriétés de chaque élément. Dans leurs tentatives de classification, plusieurs chercheurs ont remarqué des récurrences, ou périodes, dans leur classification.</p>
<section id="la-classification-périodique" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="la-classification-périodique"><span class="header-section-number">6.1</span> La classification périodique</h2>
<p>En 1871, le chimiste russe <strong>Dmitri Mendeleev</strong> (1836-1907) a présenté le premier <strong>tableau périodique</strong>. Il a classé les éléments par masse atomique croissante et il a ensuite organisé les éléments avec des propriétés chimiques similaires dans la même colonne.</p>
<p>Plus tard, le tableau périodique moderne a été introduit. Il classe les éléments par numéro atomique et non par masse atomique, mais le principe est le même que le classement de Mendeleev.</p>
<p>Chaque case du tableau représente un élément différent et contient au moins trois informations:</p>
<ul>
<li>le symbole de l’élément</li>
<li>le numéro atomique de l’élément</li>
<li>la masse atomique de l’élément</li>
</ul>
<div id="fig-tpe-case" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tpe-case-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/tpe-case.png" class="img-fluid figure-img" style="width:67.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tpe-case-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Une case du tableau périodique
</figcaption>
</figure>
</div>
<p>Le tableau périodique contient souvent des informations supplémentaires sur les éléments, il peut contenir des couleurs différentes ou il peut être écrit dans différentes langues, mais la structure de base du tableau reste la même.</p>
<section id="métaux-non-métaux-métalloïdes" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="métaux-non-métaux-métalloïdes"><span class="header-section-number">6.1.1</span> Métaux, non-métaux, métalloïdes</h3>
<p>Si aujourd’hui, 86 métaux sont présents dans le tableau de Mendeleïev, seuls sept d’entre eux étaient connus et isolés jusqu’au Moyen Age :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">élément</th>
<th style="text-align: left;">découverte</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">or</td>
<td style="text-align: left;">6000 av. J.-C.</td>
</tr>
<tr class="even">
<td style="text-align: left;">cuivre</td>
<td style="text-align: left;">4000 av. J.-C.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">argent</td>
<td style="text-align: left;">3500 av. J.-C.</td>
</tr>
<tr class="even">
<td style="text-align: left;">plomb</td>
<td style="text-align: left;">3500 av. J.-C.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">étain</td>
<td style="text-align: left;">3000 av. J.-C.</td>
</tr>
<tr class="even">
<td style="text-align: left;">fer</td>
<td style="text-align: left;">1500 av. J.-C.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mercure</td>
<td style="text-align: left;">750 av. J.-C.</td>
</tr>
</tbody>
</table>
<p>Les <strong>métaux</strong> sont solides à température et pression ambiante, à l’exception du mercure qui est liquide. Ils ont une apparence brillante et sont de bons conducteurs de la chaleur et de l’électricité. Ils sont malléables et ductiles.</p>
<p>Les éléments B, Si, Ge, As, Sb, Te, Po et At sont appelés <strong>métalloïdes</strong>. Les métalloïdes ont les propriétés des métaux et des non-métaux. Leurs propriétés électriques inhabituelles sont employée dans l’industrie des semi-conducteurs et en fabrication informatique.</p>
<p>Le reste des éléments, à droite des métalloïdes, sont appelés <strong>non-métaux</strong>. Les non-métaux ont des propriétés qui sont souvent opposées à celles des métaux. Certains sont des gaz, ils sont de mauvais conducteurs de la chaleur et de l’électricité, ils ne sont ni malléables, ni ductiles.</p>
<div id="fig-tpe-empty" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tpe-empty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/tpe-empty.png" class="img-fluid figure-img" style="width:45.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tpe-empty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Le vocabulaire du tableau périodique
</figcaption>
</figure>
</div>
<div class="Exercise">
<p>Classez chacun des éléments suivants en métal, non-métal ou métalloïde.</p>
<ol type="1">
<li>le fer (Fe)</li>
<li>le silicium (Si)</li>
<li>le soufre (S)</li>
<li>le sodium (Na)</li>
<li>le germanium (Ge)</li>
<li>l’oxygène (O)</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>fer : métal</li>
<li>silicium : métalloïde</li>
<li>soufre : non-métal</li>
<li>sodium : métal</li>
<li>germanium : métalloïde</li>
<li>oxygène : non-métal</li>
</ol>
</div>
</section>
<section id="les-périodes" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="les-périodes"><span class="header-section-number">6.1.2</span> Les périodes</h3>
<p>Les <strong>lignes</strong> du tableau périodique sont appelées <strong>périodes</strong> et chacune est désignée par un nombre de 1 à 7 (première période, deuxième période, etc.). Le nom de tableau périodique provient du fait que les propriétés reviennent périodiquement à chaque fois qu’on change de ligne.</p>
<p>Le tableau périodique regroupe les éléments par période, mais les propriétés chimiques des éléments d’une même période sont différentes. Le classement par période représente l’arrangement des électrons au sein des éléments.</p>
</section>
<section id="les-familles" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="les-familles"><span class="header-section-number">6.1.3</span> Les familles</h3>
<p>Les <strong>colonnes</strong> du tableau périodique sont appelées <strong>familles</strong>. Le tableau périodique classe les éléments de sorte que les éléments ayant des propriétés chimiques similaires apparaissent dans la même colonne formant ainsi une famille d’éléments.</p>
<p>Il y a au total 18 familles et il existe différentes manières de les numéroter. Dans votre tableau périodique, les familles du <strong>groupe principal</strong> sont désignées avec un chiffre romain de I à VIII. Vous verrez peut-être d’autres numérotations, l’Union Internationale de Chimie Pure et Appliquée (UICPA) a décidé que le système officiel de numérotation des groupes serait de 1 à 18, de gauche à droite. De nombreux tableaux périodiques présentent plusieurs systèmes simultanément.</p>
<!-- Les familles qui sont désigné avec un A sont appelés les **éléments de groupe principal**, les familles qui sont désigné avec un B sont appelés les **éléments de transition**. -->
<div id="tbl-noms-groupes-courants" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-noms-groupes-courants-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Noms de quelques groupes couramment employés.
</figcaption>
<div aria-describedby="tbl-noms-groupes-courants-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Groupe</th>
<th style="text-align: left;">nom</th>
<th style="text-align: left;">éléments</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">I</td>
<td style="text-align: left;">métaux alcalins</td>
<td style="text-align: left;">Li, Na, K, Rb, Cs, Fr</td>
</tr>
<tr class="even">
<td style="text-align: center;">II</td>
<td style="text-align: left;">métaux alcalino-terreux</td>
<td style="text-align: left;">Be, Mg, Ca, Sr, Ba, Ra</td>
</tr>
<tr class="odd">
<td style="text-align: center;">VI</td>
<td style="text-align: left;">chalcogènes</td>
<td style="text-align: left;">O, S, Se, Te, Po</td>
</tr>
<tr class="even">
<td style="text-align: center;">VII</td>
<td style="text-align: left;">halogènes</td>
<td style="text-align: left;">F, Cl, Br, I, At</td>
</tr>
<tr class="odd">
<td style="text-align: center;">VIII</td>
<td style="text-align: left;">les gaz rares (ou gaz nobles)</td>
<td style="text-align: left;">He, Ne, Ar, Kr, Xe, Rn</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Les <strong>éléments de transition internes</strong> ont été décalés dans le tableau périodique afin de rendre ce dernier plus compact.</p>
<div class="Exercise">
<p>À l’aide du tableau périodique, indiquez pour chaque élément sa période, son groupe et, s’il en possède un, le nom de sa famille.</p>
<ol type="1">
<li>le sodium (Na)</li>
<li>le calcium (Ca)</li>
<li>le chlore (Cl)</li>
<li>l’argon (Ar)</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>sodium : période 3, groupe I, métaux alcalins</li>
<li>calcium : période 4, groupe II, métaux alcalino-terreux</li>
<li>chlore : période 3, groupe VII, halogènes</li>
<li>argon : période 3, groupe VIII, gaz rares (gaz nobles)</li>
</ol>
</div>
</section>
</section>
<section id="interactions-rayonnement-matière" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="interactions-rayonnement-matière"><span class="header-section-number">6.2</span> Interactions rayonnement-matière</h2>
<p>Une onde est une perturbation de l’état physique d’un milieu qui se propage. Elle transporte de l’énergie sans transporter de matière. Par exemple, lorsqu’on lance un caillou dans l’eau, la surface de l’eau est modifiée et des vagues apparaissent à sa surface; lorsque l’on frappe dans ses mains, cette variation de pression de propage dans l’air ambiant; quand on frotte une corde de violon avec un archet, on peut voir la corde vibrer et l’entendre grâce à la propagation de la vibration dans l’air.</p>
<p>Les objets quantiques, comme la lumière et les électrons, ont la particularité de se comporter <strong>à la fois</strong> comme des ondes ou des particules. Un électron a, par exemple, une masse et une charge électrique. Il peut être défini comme une particule. Alors que si on laisse cet électron se déplacer librement sans l’observer, il aura les caractéristiques d’une onde. Pour expliquer la structure et le comportement des atomes, il est nécessaire de considérer que les particules ont des propriétés ondulatoires.</p>
<section id="les-ondes-électromagnétiques" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="les-ondes-électromagnétiques"><span class="header-section-number">6.2.1</span> Les ondes électromagnétiques</h3>
<p>Les ondes qui vont nous intéresser pour décrire les électrons sont les <strong>ondes électromagnétiques</strong>. Une onde électromagnétique est une perturbation du champ électromagnétique qui se propage. Elle a la particularité de se propager aussi bien dans un milieu matériel que dans le vide. Les ondes radio, les ondes lumineuses ou les rayons X sont des exemples d’onde électromagnétique.</p>
</section>
<section id="longueur-donde-fréquence-et-énergie" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="longueur-donde-fréquence-et-énergie"><span class="header-section-number">6.2.2</span> Longueur d’onde, fréquence et énergie</h3>
<p>Si on dessine un faisceau lumineux sous la forme d’une onde, nous appellerons <strong>longueur d’onde</strong>, la distance entre deux crêtes (ou entre deux creux ou entre deux positions identiques sur l’onde). Si on considère que cette onde se déplace de gauche à droite et si on compte le nombre de crêtes qui passent par un point particulier chaque seconde, on obtient la <strong>fréquence</strong>.</p>
<div id="fig-ondes-electromagnetiques" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ondes-electromagnetiques-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/ondes-electromagnetiques.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ondes-electromagnetiques-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Longueur d’onde, fréquence et énergie
</figcaption>
</figure>
</div>
<p>La longuer d’onde est exprimée en nanomètre, nm, pour les ondes lumineuses. La fréquence est exprimée en Hertz, Hz, le nombre de cycles par seconde. Longueur d’onde et fréquence sont inversément proportionnelles. Plus la longueur d’onde est élevée, plus la fréquence est basse. Plus la longueur d’onde est petite, plus la fréquence est élevée.</p>
<p>La relation de Planck permet de mettre en relation la fréquence et l’énergie d’un photon selon l’équation :</p>
<p><span class="math display">\[
\begin{split}
E = h \cdot \nu
\end{split}
\qquad
\text{ou}
\qquad
\begin{split}
E = h \cdot \frac{c}{\lambda}
\end{split}
\qquad
\begin{split}
E &amp; \text{ : énergie du photon, en } \text{ J} \\
h &amp; \text{ : constante de Planck, } 6.625 \cdot 10^{-34}\ \text{ J}\cdot\text{s} \\
\nu &amp; \text{ : fréquence, en } \text{ Hz} \\
\lambda &amp; \text{ : longueur d'onde, en } \text{ m} \\
c &amp; \text{ : vitesse de la lumière, } 3 \cdot 10^{8}\ \text{ m}\cdot\text{s}^{-1}
\end{split}
\]</span></p>
<div class="Exercise">
<p>Une lumière verte a une longueur d’onde de 550 nm. On rappelle : <span class="math inline">\(c = 3\cdot10^{8}\)</span> m/s et <span class="math inline">\(h = 6.625\cdot10^{-34}\)</span> J·s.</p>
<ol type="1">
<li>Convertissez cette longueur d’onde en mètres. </li>
<li>Calculez la fréquence de cette lumière. </li>
<li>Calculez l’énergie d’un photon de cette lumière. </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><span class="math inline">\(\lambda = 550 \text{ nm} = 550\cdot10^{-9} \text{ m} = 5.50\cdot10^{-7} \text{ m}\)</span>.</li>
<li><span class="math display">\[
\nu = \frac{c}{\lambda} = \frac{3\cdot10^{8}}{5.50\cdot10^{-7}} = 5.45\cdot10^{14} \text{ Hz}
\]</span></li>
<li><span class="math display">\[
E = h \cdot \nu = 6.625\cdot10^{-34} \cdot 5.45\cdot10^{14} = 3.61\cdot10^{-19} \text{ J}
\]</span></li>
</ol>
</div>
</section>
<section id="le-spectre-électromagnétique" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="le-spectre-électromagnétique"><span class="header-section-number">6.2.3</span> Le spectre électromagnétique</h3>
<p>L’analyse du rayonnement émis ou absorbé par la matière s’appelle la <strong>spectroscopie</strong>.</p>
<p>Le spectre électromagnétique regroupe l’ensemble de toutes les ondes électromagnétiques en fonction de leur longueur d’onde et de leur fréquence.</p>
<div id="fig-domaine-spectre-electromagnetique" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-domaine-spectre-electromagnetique-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/domaine-spectre-electromagnetique.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-domaine-spectre-electromagnetique-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Domaines du spectre électromagnétique.
</figcaption>
</figure>
</div>
<div class="credit">
<p>crédit : wikimedia/Benjamin ABEL</p>
</div>
<p>Les ondes électromagnétiques sont classées en différentes catégories selon leur longueur d’onde. Les plus connues sont celles de la lumière visible (entre 400 et 750 nm, environ) mais il existe d’autres rayonnements que l’oeil ne perçoit pas.</p>
<div id="tbl-domaine-spectre-visible" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-domaine-spectre-visible-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Domaine du spectre visible.
</figcaption>
<div aria-describedby="tbl-domaine-spectre-visible-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 33%">
<col style="width: 35%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">couleur</th>
<th style="text-align: center;">longueur d’onde nm</th>
<th style="text-align: center;">fréquence 10<sup>14</sup> Hz</th>
<th style="text-align: center;">énergie eV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">violet</td>
<td style="text-align: center;">400</td>
<td style="text-align: center;">7.50</td>
<td style="text-align: center;">3.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">bleu</td>
<td style="text-align: center;">450</td>
<td style="text-align: center;">6.66</td>
<td style="text-align: center;">2.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cyan</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">5.99</td>
<td style="text-align: center;">2.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">vert</td>
<td style="text-align: center;">550</td>
<td style="text-align: center;">5.45</td>
<td style="text-align: center;">2.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">jaune</td>
<td style="text-align: center;">580</td>
<td style="text-align: center;">5.16</td>
<td style="text-align: center;">2.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">orange</td>
<td style="text-align: center;">600</td>
<td style="text-align: center;">5.00</td>
<td style="text-align: center;">2.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rouge</td>
<td style="text-align: center;">650</td>
<td style="text-align: center;">4.62</td>
<td style="text-align: center;">1.91</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="interactions-rayonnement-matière-1" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="interactions-rayonnement-matière-1"><span class="header-section-number">6.2.4</span> Interactions rayonnement-matière</h3>
<p>Nous sommes régulièrement confrontés à des interactions entre la matière (les atomes) et un rayonnement électromagnétique. Par exemple, un morceau de fer chauffé va émettre un rayonnement électromagnétique différent selon la température à laquelle il est porté. On peut aussi voir l’absorption de rayonnement comme lors d’une radiographie au rayons X. Les os absorbent les rayons X alors que les tissus mous (peau, graisse, muscles) sont quasiment transparents aux rayons X.</p>
<p>Des ondes électromagnétiques peuvent être absorbées par un électron augmentant ainsi son niveau d’énergie au-delà de son <strong>état fondamental</strong>. Toutefois, un électron n’absorbera une onde que si celle-ci lui permet d’atteindre un niveau d’énergie bien précis. On parlera alors de <strong>transition électronique</strong> et si l’électron évolue vers un état d’énergie plus élevé, on parlera d’<strong>excitation électronique</strong>.</p>
<p>Un électron qui se trouve dans un état d’énergie supérieure à celle de l’état fondamental va avoir tendance à évoluer vers un état d’énergie plus faible avec l’émission d’une onde électromagnétique. L’électron va donc perdre de l’énergie en éjectant un photon qui possède exactement la différence d’énergie entre les deux états.</p>
<div id="fig-absorption-emission" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-absorption-emission-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/absorption-emission.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-absorption-emission-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: Différence entre spectres d’absorption et d’émission
</figcaption>
</figure>
</div>
<p>L’électron absorbe de l’énergie tout en restant au sein de l’atome et finira toujours par la réémettre sous forme d’une onde électromagnétique. La mesure de ces quantités de lumière émises ou absorbées forment le principe de base de la spectroscopie.</p>
<div class="Exercise">
<p>Répondez aux questions suivantes sur l’interaction entre la lumière et les électrons.</p>
<ol type="1">
<li>Qu’appelle-t-on une transition électronique ? </li>
<li>Un électron qui passe de l’état fondamental à un état excité absorbe-t-il ou émet-il un photon ? </li>
<li>Un électron qui revient d’un état excité vers l’état fondamental absorbe-t-il ou émet-il un photon ? </li>
<li>Quelle relation y a-t-il entre l’énergie du photon échangé et les deux niveaux d’énergie de l’électron ? </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>C’est le passage d’un électron d’un niveau d’énergie à un autre au sein de l’atome.</li>
<li>Il <strong>absorbe</strong> un photon : il gagne de l’énergie, c’est une excitation.</li>
<li>Il <strong>émet</strong> un photon : il perd de l’énergie.</li>
<li>L’énergie du photon absorbé ou émis est exactement égale à la <strong>différence d’énergie</strong> entre les deux niveaux.</li>
</ol>
</div>
</section>
</section>
<section id="les-orbitales-atomiques" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="les-orbitales-atomiques"><span class="header-section-number">6.3</span> Les orbitales atomiques</h2>
<p>Dans les années 1900 Schrödinger développe un modèle atomique plus évolué en utilisant la mécanique quantique, le <strong>modèle standard</strong>.</p>
<p>Ce modèle introduit une description mathématique du mouvement de l’électron appelée <strong>orbitale atomique</strong>. Une orbitale représente un volume de l’espace dans lequel la probabilité de trouver un électron est élevée.</p>
<div id="tbl-couches-sous-couches-orbitales" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-couches-sous-couches-orbitales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: Résumé des couches, sous-couches et orbitales.
</figcaption>
<div aria-describedby="tbl-couches-sous-couches-orbitales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">couche</th>
<th style="text-align: center;">sous-couche</th>
<th style="text-align: center;">orbitales</th>
<th style="text-align: center;">électrons</th>
<th style="text-align: center;">total électrons</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: center;">s</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><strong>2</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: center;">s</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><strong>8</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">p</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: center;">s</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><strong>18</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">p</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">d</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>4</strong></td>
<td style="text-align: center;">s</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><strong>32</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">p</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">d</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">f</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Selon ce modèle, les électrons d’un atome gravitent autour de l’atome à des niveaux d’énergie différents. Ces niveaux sont appelés <strong>couches</strong> et sont situés à différentes distances du noyau. Les couches sont numérotées de 1 à 7 et plus le numéro de la couche est petit, plus la couche est proche du noyau.</p>
<p>Dans une couche les électrons sont distribués en <strong>sous-couches</strong> d’énergie légèrement différentes. On note les sous-couches avec les lettres s, p, d, f et chacune représente une forme d’orbitale différente.</p>
<div id="fig-orb-3d" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-orb-3d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/orb-3d.jpeg" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-orb-3d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.6: Formes des orbitales s, p et d.
</figcaption>
</figure>
</div>
<div class="credit">
<p>crédit : wikimedia/haade</p>
</div>
<p>Les électrons d’une sous-couche peuvent être répartis dans des volumes d’énergie égale appelés orbitales. Il y a une orbitale pour une sous-couche <em>s</em>, trois orbitales pour une <em>p</em>, cinq pour une <em>d</em>, sept pour un <em>f</em>. Une orbitale ne peut être occupée que par deux électrons.</p>
<section id="la-configuration-électronique" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="la-configuration-électronique"><span class="header-section-number">6.3.1</span> La configuration électronique</h3>
<p>La manière dont les électrons sont répartis dans les différentes orbitales peut être représenté par un <strong>diagramme des orbitales atomiques</strong>. Dans ce type de diagramme, les orbitales sont représentées par des cases dans lesquels on place les électrons à disposition. L’orbitale 1s a le niveau d’énergie le plus bas et est la plus proche du noyau.</p>
<p>On utilise ce diagramme pour prédire les liaisons qui se produisent entre deux atomes et pour montrer pourquoi certains éléments se comportent de la même façon.</p>
<div id="fig-energy-level" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-energy-level-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/energy-level.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-energy-level-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.7: Diagramme énergétique des orbitales atomiques.
</figcaption>
</figure>
</div>
</section>
<section id="déterminer-une-configuration-électronique" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="déterminer-une-configuration-électronique"><span class="header-section-number">6.3.2</span> Déterminer une configuration électronique</h3>
<div id="fig-energy-level-order" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-energy-level-order-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/energy-level-order.png" class="img-fluid figure-img" style="width:25.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-energy-level-order-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.8: Ordre de remplissage des orbitales.
</figcaption>
</figure>
</div>
<p>En connaissant le nombre d’électrons contenus dans un atome, on peut remplir ce diagramme en respectant certaines règles:</p>
<ul>
<li>Les électrons sont placés dans la sous-couche disponible de plus basse énergie.</li>
<li>On peut placer au maximum 2 électrons dans une orbitale (exclusion de Pauli).</li>
<li>La <a href="#fig-energy-level-order" class="quarto-xref">Figure&nbsp;<span>6.8</span></a> donne l’ordre de remplissage des orbitales (principe Aufbau).</li>
<li>Si plusieurs orbitales de même énergie sont disponibles, on remplit le plus d’orbitales possibles avant d’apparier les électrons.</li>
</ul>
<p>Une fois le diagramme rempli, on en déduit la configuration électronique de l’atome pour le niveau de plus basse énergie. La <strong>configuration électronique</strong> d’un atome est une notation abrégée de la répartition des électrons dans les différentes couches et sous-couches électroniques.</p>
<div class="Exercise-container">
<div class="Exercise">
<p>A l’aide des diagrammes suivants, déterminez la configuration électronique de l’atome de carbone et celle de l’atome de sodium :</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">atome de carbone</th>
<th style="text-align: left;">atome de sodium</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><img src="images/energy-level-2.png" class="img-fluid" style="width:40.0%"></td>
<td style="text-align: left;"><img src="images/energy-level-2.png" class="img-fluid" style="width:40.0%"></td>
</tr>
<tr class="even">
<td style="text-align: left;">nombre d’électrons :</td>
<td style="text-align: left;">nombre d’électrons :</td>
</tr>
<tr class="odd">
<td style="text-align: left;">structure électronique :</td>
<td style="text-align: left;">structure électronique :</td>
</tr>
</tbody>
</table>
</div>
<div class="Answer">
<ul>
<li>atome de carbone<br>
<img src="images/energy-level-2-2.png" class="img-fluid" style="width:33.0%">
<ul>
<li>nombre d’électrons : <strong>6</strong></li>
<li>structure électronique : <span class="math inline">\(1s^2 2s^2 2p^2\)</span></li>
</ul></li>
<li>atome de sodium<br>
<img src="images/energy-level-2-3.png" class="img-fluid" style="width:33.0%">
<ul>
<li>nombre d’électrons : <strong>11</strong></li>
<li>structure électronique : <span class="math inline">\(1s^2 2s^2 2p^6 3s^1\)</span></li>
</ul></li>
</ul>
</div>
<p>Pour simplifier la notation de la configuration électronique, on indique que les électrons de la dernière couche électronique. On remplace les autres couches par le symbole du gaz rare le plus proche entre crochets. Par exemple, la structure électronique du chlore (Cl) :</p>
<p><span class="math display">\[ \underbrace{1s^{2}~2s^{2}~2p^{6}}_{\text{Néon}}~3s^{2}~3p^{5} \text{ devient } [Ne]~3s^{2}~3p^{5} \]</span></p>
<div id="tbl-conf-elec-premieres-periodes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-conf-elec-premieres-periodes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.4: Configuration électronique des deux premières périodes.
</figcaption>
<div aria-describedby="tbl-conf-elec-premieres-periodes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 37%">
<col style="width: 8%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Groupe</th>
<th style="text-align: center;">Elément</th>
<th style="text-align: left;">Conf. électronique</th>
<th style="text-align: center;">Elément</th>
<th style="text-align: left;">Conf. électronique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">I</td>
<td style="text-align: center;">Li</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{1}\)</span></td>
<td style="text-align: center;">Na</td>
<td style="text-align: left;">[Ne] <span class="math inline">\(3s^{1}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">II</td>
<td style="text-align: center;">Be</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{2}\)</span></td>
<td style="text-align: center;">Mg</td>
<td style="text-align: left;">[Ne] <span class="math inline">\(3s^{2}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">III</td>
<td style="text-align: center;">B</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{2}~2p^{1}\)</span></td>
<td style="text-align: center;">Al</td>
<td style="text-align: left;">[Ne] <span class="math inline">\(3s^{2}~3p^{1}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">IV</td>
<td style="text-align: center;">C</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{2}~2p^{2}\)</span></td>
<td style="text-align: center;">Si</td>
<td style="text-align: left;">[Ne] <span class="math inline">\(3s^{2}~3p^{2}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">V</td>
<td style="text-align: center;">N</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{2}~2p^{3}\)</span></td>
<td style="text-align: center;">P</td>
<td style="text-align: left;">[Ne] <span class="math inline">\(3s^{2}~3p^{3}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">VI</td>
<td style="text-align: center;">O</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{2}~2p^{4}\)</span></td>
<td style="text-align: center;">S</td>
<td style="text-align: left;">[Ne] <span class="math inline">\(3s^{2}~3p^{4}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">VII</td>
<td style="text-align: center;">F</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{2}~2p^{5}\)</span></td>
<td style="text-align: center;">Cl</td>
<td style="text-align: left;">[Ne] <span class="math inline">\(3s^{2}~3p^{5}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">VIII</td>
<td style="text-align: center;">Ne</td>
<td style="text-align: left;">[He] <span class="math inline">\(2s^{2}~2p^{6} \equiv\)</span> [Ne]</td>
<td style="text-align: center;">Ar</td>
<td style="text-align: left;">[He] <span class="math inline">\(3s^{2}~3p^{6} \equiv\)</span> [Ar]</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="Exercise">
<p>Pour chacun des éléments suivants, écrivez la configuration électronique complète, puis la configuration simplifiée (à l’aide du gaz rare précédent).</p>
<ol type="1">
<li>l’azote (N, Z = 7)</li>
<li>le magnésium (Mg, Z = 12)</li>
<li>le chlore (Cl, Z = 17)</li>
<li>le potassium (K, Z = 19)</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>N : <span class="math inline">\(1s^{2}\,2s^{2}\,2p^{3}\)</span> <span class="math inline">\(\equiv\)</span> [He]<span class="math inline">\(\,2s^{2}\,2p^{3}\)</span></li>
<li>Mg : <span class="math inline">\(1s^{2}\,2s^{2}\,2p^{6}\,3s^{2}\)</span> <span class="math inline">\(\equiv\)</span> [Ne]<span class="math inline">\(\,3s^{2}\)</span></li>
<li>Cl : <span class="math inline">\(1s^{2}\,2s^{2}\,2p^{6}\,3s^{2}\,3p^{5}\)</span> <span class="math inline">\(\equiv\)</span> [Ne]<span class="math inline">\(\,3s^{2}\,3p^{5}\)</span></li>
<li>K : <span class="math inline">\(1s^{2}\,2s^{2}\,2p^{6}\,3s^{2}\,3p^{6}\,4s^{1}\)</span> <span class="math inline">\(\equiv\)</span> [Ar]<span class="math inline">\(\,4s^{1}\)</span></li>
</ol>
</div>
<p>La configuration électronique du niveau de plus basse énergie est appelée <strong>état fondamental</strong>. Les configurations dont la distribution des électrons est différente de l’état fondamental sont appelées <strong>états excités</strong>.</p>
<div id="fig-energy-level-5" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-energy-level-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/energy-level-5.png" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/tpe-orbitals.png" class="img-fluid figure-img"></p>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-energy-level-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.9: Les orbitales atomiques et le tableau périodique.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="les-électrons-de-valence" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="les-électrons-de-valence"><span class="header-section-number">6.4</span> Les électrons de valence</h2>
<div class="tcolorbox">
<p><strong>Les électrons de valence</strong><br>
Les électrons de valence sont les électrons de la dernière couche électronique d’un atome.</p>
</div>
<p>Lorsqu’un chimiste étudie une réaction, il étudie les électrons transféré entre les acteurs de la réaction. Les électrons dont le niveau d’énergie est le plus éloigné du noyau seront retenus de manière moins forte. Ce sont donc ces électrons qui seront impliqués dans les réactions.</p>
<div id="fig-configuration-electronique" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-configuration-electronique-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/configuration-electronique.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-configuration-electronique-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.10: Répartition électronique des trois premières périodes.
</figcaption>
</figure>
</div>
<div class="Exercise">
<p>Pour chaque élément, donnez le nombre d’électrons de valence et le groupe auquel il appartient.</p>
<ol type="1">
<li>le sodium (Na)</li>
<li>le carbone (C)</li>
<li>l’oxygène (O)</li>
<li>le fluor (F)</li>
<li>le néon (Ne)</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>sodium : 1 électron de valence, groupe I</li>
<li>carbone : 4 électrons de valence, groupe IV</li>
<li>oxygène : 6 électrons de valence, groupe VI</li>
<li>fluor : 7 électrons de valence, groupe VII</li>
<li>néon : 8 électrons de valence, groupe VIII</li>
</ol>
</div>
<p>Le chimiste américain <strong>G. N. Lewis</strong> (1875-1946) a proposé un moyen simple de représenter les électrons de valence d’un atome. C’est ce qu’on appelle la <strong>structure de Lewis</strong>.</p>
<p>On utilise les règles suivantes pour dessiner la structure de Lewis d’un atome:</p>
<ul>
<li>Le nombre d’électrons de valence est égal au numéro du groupe (I à VIII).</li>
<li>On place un point à la fois sur chacun des quatre côtés du symbole de l’élément.</li>
<li>On continue d’ajouter des points, en les appariant, jusqu’à ce que tous les électrons de valence soient utilisés.</li>
</ul>
<div id="tbl-structure-lewis-groupe-principal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-structure-lewis-groupe-principal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.5: Structure de Lewis des éléments du groupe principal (c = célibataire, p = paire).
</figcaption>
<div aria-describedby="tbl-structure-lewis-groupe-principal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">I</th>
<th style="text-align: center;">II</th>
<th style="text-align: center;">III</th>
<th style="text-align: center;">IV</th>
<th style="text-align: center;">V</th>
<th style="text-align: center;">VI</th>
<th style="text-align: center;">VII</th>
<th style="text-align: center;">VIII</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><img src="images/lewis-dots-1c.png" class="img-fluid figure-img" style="width:3em"></td>
<td style="text-align: center;"><img src="images/lewis-dots-2c.png" class="img-fluid figure-img" style="width:3em"></td>
<td style="text-align: center;"><img src="images/lewis-dots-3c.png" class="img-fluid figure-img" style="width:3em"></td>
<td style="text-align: center;"><img src="images/lewis-dots-4c.png" class="img-fluid figure-img" style="width:3em"></td>
<td style="text-align: center;"><img src="images/lewis-dots-1p3c.png" class="img-fluid figure-img" style="width:3em"></td>
<td style="text-align: center;"><img src="images/lewis-dots-2p2c.png" class="img-fluid figure-img" style="width:3em"></td>
<td style="text-align: center;"><img src="images/lewis-dots-3p1c.png" class="img-fluid figure-img" style="width:3em"></td>
<td style="text-align: center;"><img src="images/lewis-dots-4p.png" class="img-fluid figure-img" style="width:3em"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1c</td>
<td style="text-align: center;">2c</td>
<td style="text-align: center;">3c</td>
<td style="text-align: center;">4c</td>
<td style="text-align: center;">1p 3c</td>
<td style="text-align: center;">2p 2c</td>
<td style="text-align: center;">3p 1c</td>
<td style="text-align: center;">4p</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="Exercise-container">
<div class="Exercise">
<p>Dessinez la structure de Lewis des éléments des trois premières périodes.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">I</th>
<th style="text-align: center;">II</th>
<th style="text-align: center;">II</th>
<th style="text-align: center;">IV</th>
<th style="text-align: center;">V</th>
<th style="text-align: center;">VI</th>
<th style="text-align: center;">VII</th>
<th style="text-align: center;">VII</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Hydrogène</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">Hélium</td>
</tr>
<tr class="even">
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Lithium</td>
<td style="text-align: center;">Béryllium</td>
<td style="text-align: center;">Bore</td>
<td style="text-align: center;">Carbone</td>
<td style="text-align: center;">Azote</td>
<td style="text-align: center;">Oxygène</td>
<td style="text-align: center;">Fluor</td>
<td style="text-align: center;">Néon</td>
</tr>
<tr class="even">
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sodium</td>
<td style="text-align: center;">Magnésium</td>
<td style="text-align: center;">Aluminium</td>
<td style="text-align: center;">Silicium</td>
<td style="text-align: center;">Phosphore</td>
<td style="text-align: center;">Soufre</td>
<td style="text-align: center;">Chlore</td>
<td style="text-align: center;">Argon</td>
</tr>
<tr class="even">
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
</tr>
</tbody>
</table>
</div>
<div class="Jeu">
<p><strong>Jeu en ligne</strong> — Entraînez-vous à trouver la bonne structure de Lewis à partir des informations fournies sur <a href="https://isotope.ch/lewis">isotope.ch/lewis</a>.</p>
</div>
</section>
<section id="la-règle-de-loctet" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="la-règle-de-loctet"><span class="header-section-number">6.5</span> La règle de l’octet</h2>
<p>Les gaz rares (groupe VIII) sont très peu réactifs car ils ont une très grande stabilité électronique. Ceci est dû au fait que leur couche électronique de valence est complètement remplie avec <strong>huit électrons</strong>, à l’exception de l’hélium, qui en a deux.</p>
<p>Cette observation a conduit à une règle connue sous le nom de <strong>règle de l’octet</strong>.</p>
<div class="tcolorbox">
<p><strong>Règle de l’octet</strong><br>
Les atomes ont tendance à gagner, perdre, ou partager des électrons pour avoir huit électrons dans leur couche de valence.</p>
</div>
<p>Le remplissage complet de la couche électronique de valence est le moteur des réactions chimiques.</p>
</section>
<section id="les-ions" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="les-ions"><span class="header-section-number">6.6</span> Les ions</h2>
<div class="tcolorbox">
<p><strong>Ion</strong><br>
Un ion est un atome ou un groupe d’atomes qui a gagné ou perdu un ou plusieurs électrons.</p>
</div>
<p>Les atomes qui <strong>perdent</strong> un ou plusieurs électrons ont un excédent de charge positive et sont appelés <strong>cations</strong>.</p>
<section id="le-cation-ou-la-perte-délectrons" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="le-cation-ou-la-perte-délectrons"><span class="header-section-number">6.6.1</span> Le cation ou la perte d’électrons</h3>
<p>Prenons, par exemple, le sodium. Son numéro atomique est égal à 11, il contient 11 protons et comme l’atome est neutre, il contient également 11 électrons. Avec un électron en moins, l’atome est constitué de 11 protons et 10 électrons. Il a donc une charge positive en excès. il devient un cation. On écrira le cation sodium <strong>Na<sup>+</sup></strong>.</p>
<p><span class="math display">\[ \begin{split}
        Na \rightarrow Na^+ + 1e^-
    \end{split}
    \qquad
    \begin{split}
        11\:p^{+}\:+\:10\:e^{-}\:=\:\text{1 charge positive}\:=\:+1
    \end{split} \]</span></p>
<p>Les atomes qui ont des configurations électroniques équivalentes sont appelés <strong>isoélectroniques</strong>. Le cation sodium est isoélectronique avec le néon.</p>
</section>
<section id="lanion-ou-le-gain-délectrons" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="lanion-ou-le-gain-délectrons"><span class="header-section-number">6.6.2</span> L’anion ou le gain d’électrons</h3>
<p>Les atomes qui <strong>gagnent</strong> un ou plusieurs électrons ont un excédent de charge négative et sont appelés <strong>anions</strong>.</p>
<p>Prenons, par exemple, le chlore. Son numéro atomique est égal à 17, il contient 17 protons et 17 électrons. Avec un électron en plus, l’atome est constitué de 17 protons et 18 électrons. Il a donc une charge négative en excès. il devient un anion. On écrira l’anion chlore <strong>Cl<sup>-</sup></strong>.</p>
<p><span class="math display">\[ \begin{split}
        Cl + 1e^- \rightarrow Cl^-
    \end{split}
    \qquad
    \begin{split}
        17\:p^{+}\:+\:18\:e^{-}\:=\:\text{1 charge négative}\:=\: -1
    \end{split} \]</span></p>
<p>L’anion chlore est isoélectronique avec l’argon.</p>
<div class="Exercise">
<p>Déterminer quelle sera la charge des atomes correspondant aux description suivante:</p>
<ol type="1">
<li>Un atome ayant perdu deux électrons<br>
</li>
<li>Un atome ayant gagné un électron<br>
</li>
<li>Un atome ayant perdu trois électrons<br>
</li>
<li>Un atome ayant gagné deux électrons<br>
</li>
<li>Un atome ayant perdu un électron<br>
</li>
<li>Un atome ayant gagné trois électrons</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>0 - (2e-) = +2</li>
<li>0 + (1e-) = -1</li>
<li>0 - (3e-) = +3</li>
<li>0 + (2e-) = -2</li>
<li>0 - (1e-) = +1</li>
<li>0 + (3e-) = -3</li>
</ol>
</div>
</section>
<section id="les-ions-stables---groupe-a" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="les-ions-stables---groupe-a"><span class="header-section-number">6.6.3</span> Les ions stables - groupe A</h3>
<p>Le gain ou la perte de un, deux, ou parfois même trois électrons est possible, mais en général, un atome ne perd ou ne gagne pas plus de trois électrons.</p>
<p>La règle de l’octet nous indique qu’un atome avec huit électrons dans sa couche électronique de valence devient énergétiquement stable. Les <strong>ions stables</strong> formés par les atomes sont donc ceux qui confirment la règle de l’octet.</p>
<p>Dans le tableau périodique, les chiffres romains des groupes A indiquent le nombre d’électrons de valence de chaque élément. On peut utiliser la position d’un élément dans le tableau pour déterminer quel sera l’ion stable formé par cet élément.</p>
<div class="Exercise-container">
<div class="Exercise">
<p>Représenter sous leur forme symbolique les ions stables formés par les éléments des périodes n°2 et n°3.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">I</th>
<th style="text-align: center;">II</th>
<th style="text-align: center;">II</th>
<th style="text-align: center;">IV</th>
<th style="text-align: center;">V</th>
<th style="text-align: center;">VI</th>
<th style="text-align: center;">VII</th>
<th style="text-align: center;">VII</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Lithium</td>
<td style="text-align: center;">Béryllium</td>
<td style="text-align: center;">Bore</td>
<td style="text-align: center;">Carbone</td>
<td style="text-align: center;">Azote</td>
<td style="text-align: center;">Oxygène</td>
<td style="text-align: center;">Fluor</td>
<td style="text-align: center;">Néon</td>
</tr>
<tr class="even">
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sodium</td>
<td style="text-align: center;">Magnésium</td>
<td style="text-align: center;">Aluminium</td>
<td style="text-align: center;">Silicium</td>
<td style="text-align: center;">Phosphore</td>
<td style="text-align: center;">Soufre</td>
<td style="text-align: center;">Chlore</td>
<td style="text-align: center;">Argon</td>
</tr>
<tr class="even">
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
<td style="text-align: center;"><img src="images/1px.png" style="height:4em"></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="les-ions-des-éléments-de-transition---groupe-b" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="les-ions-des-éléments-de-transition---groupe-b"><span class="header-section-number">6.6.4</span> Les ions des éléments de transition - groupe B</h3>
<p>Déterminer l’ion stable formé par les métaux de transition est plus difficile car ces éléments ne gagneront ou ne perderont pas toujours le même nombre d’électrons.</p>
<p>Les éléments de transition ne respectent pas la règle de l’octet, mais une autre règle appelée la <strong>règle des 18 électrons</strong>. Nous n’aborderons pas cette règle dans le cadre de ce cours.</p>
</section>
</section>
<section id="résumé" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="résumé"><span class="header-section-number">6.7</span> Résumé</h2>
<ul>
<li>Dans le tableau périodique, les éléments sont classés par numéro atomique croissant ; les lignes sont les périodes et les colonnes les familles ou groupes. Les éléments d’une même famille ont des propriétés chimiques semblables.</li>
<li>On distingue les métaux, les non-métaux et les métalloïdes, aux propriétés intermédiaires.</li>
<li>La lumière est une onde électromagnétique caractérisée par sa longueur d’onde <span class="math inline">\(\lambda\)</span> et sa fréquence <span class="math inline">\(\nu\)</span>, inversement proportionnelles (<span class="math inline">\(c = \lambda\cdot\nu\)</span>).</li>
<li>Le spectre électromagnétique classe les ondes selon leur longueur d’onde ; la lumière visible s’étend d’environ 400 nm (violet) à 750 nm (rouge).</li>
<li>Un électron peut absorber un photon pour passer à un niveau d’énergie supérieur ou émettre un photon en revenant à un niveau inférieur ; l’énergie du photon est égale à la différence entre les deux niveaux.</li>
<li>Les électrons se répartissent autour du noyau en couches, sous-couches et orbitales.</li>
<li>La configuration électronique s’obtient en remplissant les sous-couches par énergie croissante.</li>
<li>Les électrons de valence sont ceux de la dernière couche ; leur nombre correspond au numéro de groupe (I à VIII). La structure de Lewis les représente par des points autour du symbole.</li>
<li>La règle de l’octet : les atomes tendent à posséder 8 électrons de valence en gagnant, perdant ou partageant des électrons.</li>
<li>Un ion est un atome ayant gagné ou perdu des électrons : un cation (charge positive) résulte d’une perte, un anion (charge négative) d’un gain.</li>
</ul>
</section>
<section id="exercices-supplémentaires" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="exercices-supplémentaires"><span class="header-section-number">6.8</span> Exercices supplémentaires</h2>
<div class="Exercise">
<ol type="1">
<li>Donnez le symbole des éléments suivants : Magnésium, Potassium, Fer, Cuivre<br>
</li>
<li>Quel est le nom des éléments suivants : C, Cl, Au, Sb<br>
</li>
<li>Dans quelle période se trouvent les éléments suivants : He, Ge, Rb, I<br>
</li>
<li>Dans quel groupe se trouvent les éléments suivants : Soufre, Iode, Ca, Sn<br>
</li>
<li>Proposez le symbole d’un élément correspondant à chacune des descriptions suivantes :</li>
</ol>
<ul>
<li>un halogène</li>
<li>un non-métal</li>
<li>un métal alcalin</li>
<li>un élément de transition</li>
<li>un gaz rare</li>
<li>un métal alcalino-terreux</li>
</ul>
</div>
<div class="Answer">
<ol type="1">
<li>Donnez le symbole des éléments suivants :<br>
Magnésium : Mg / Potassium : K / Fer : Fe / Cuivre : Cu</li>
<li>Quel est le nom des éléments suivants :<br>
C : Carbone- Cl : Chlore / Au : Or / Sb : Antimoine</li>
<li>Dans quelle période se trouvent les éléments suivants :<br>
He : 1 / Ge : 4 / Rb : 5 / I : 5</li>
<li>Dans quel groupe se trouvent les éléments suivants : Soufre : VI / Iode : VII / Ca : II / Sn : IV</li>
<li>Exemples possibles : un halogène : Cl / un non-métal : O / un métal alcalin : Na / un élément de transition : Fe / un gaz rare : Ne / un métal alcalino-terreux : Ca</li>
</ol>
</div>
<div class="Exercise">
<p>Pour chaque descritpion ci-dessous, déterminez la charge de l’atome, indiquez si l’élément est un cation ou un anion et donnez son symbole.</p>
<ol type="1">
<li>un atome de magnésium avec 12 protons et 10 électrons<br>
</li>
<li>un atome de fluor avec 9 protons et 10 électrons<br>
</li>
<li>un atome de lithium avec 3 protons et 2 électrons<br>
</li>
<li>un atome de soufre avec 16 protons et 18 électrons</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>+2, cation, <span class="math inline">\(Mg^{2+}\)</span></li>
<li>-1, anion, <span class="math inline">\(F^-\)</span></li>
<li>+1, cation, <span class="math inline">\(Li^+\)</span></li>
<li>-2, anion, <span class="math inline">\(S^{2-}\)</span></li>
</ol>
</div>
<div class="Exercise">
<p>Donnez le nom et le symbole des éléments qui correspondent aux descriptions suivantes.</p>
<ol type="1">
<li>27 protons dans le noyau de chaque atome<br>
</li>
<li>50 électrons dans chaque atome neutre<br>
</li>
<li>18 électrons dans chaque cation +2<br>
</li>
<li>10 électrons dans chaque anion -1</li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>Cobalt / Co</li>
<li>Étain / Sn</li>
<li>Calcium / Ca</li>
<li>Fluor / F</li>
</ol>
</div>
<div class="Exercise">
<p>Indiquer le nombre de protons, de neutrons et d’électrons de chacune des espèces suivantes.</p>
<ol type="1">
<li><span class="math inline">\(^{90}Sr\)</span><br>
</li>
<li><span class="math inline">\(^{41}K\)</span><br>
</li>
<li><span class="math inline">\(^{75}_{33}As\)</span><br>
</li>
<li><span class="math inline">\(^{32}_{15}P\)</span><br>
</li>
<li><span class="math inline">\(^{90}As^{2+}\)</span></li>
<li><span class="math inline">\(^{34}_{16}S^{2-}\)</span></li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><span class="math inline">\(^{90}Sr\)</span> : 38 <span class="math inline">\(p^+\)</span> / 52 <span class="math inline">\(n\)</span> / 38 <span class="math inline">\(e^-\)</span></li>
<li><span class="math inline">\(^{41}K\)</span> : 19 <span class="math inline">\(p^+\)</span> / 22 <span class="math inline">\(n\)</span> / 19 <span class="math inline">\(e^-\)</span></li>
<li><span class="math inline">\(^{75}_{33}As\)</span> : 33 <span class="math inline">\(p^+\)</span> / 42 <span class="math inline">\(n\)</span> / 33 <span class="math inline">\(e^-\)</span></li>
<li><span class="math inline">\(^{32}_{15}P\)</span> : 15 <span class="math inline">\(p^+\)</span> / 17 <span class="math inline">\(n\)</span> / 15 <span class="math inline">\(e^-\)</span></li>
<li><span class="math inline">\(^{90}As^{2+}\)</span> : 33 <span class="math inline">\(p^+\)</span> / 57 <span class="math inline">\(n\)</span> / 31 <span class="math inline">\(e^-\)</span></li>
<li><span class="math inline">\(^{34}_{16}S^{2-}\)</span> : 16 <span class="math inline">\(p^+\)</span> / 18 <span class="math inline">\(n\)</span> / 18 <span class="math inline">\(e^-\)</span></li>
</ol>
</div>
<div class="Exercise">
<p>Dessinez le symbole de Lewis de chacun des éléments suivants : Al, Br, Ar, Ca.</p>
</div>
<div class="Answer">
<p>Le nombre d’électrons de valence est donné par le numéro de groupe.</p>
<ul>
<li>Al (groupe III) : 3 électrons de valence, soit 3 points célibataires (3c).</li>
<li>Br (groupe VII) : 7 électrons de valence, soit 3 paires et 1 célibataire (3p 1c).</li>
<li>Ar (groupe VIII) : 8 électrons de valence, soit 4 paires (4p).</li>
<li>Ca (groupe II) : 2 électrons de valence, soit 2 points célibataires (2c).</li>
</ul>
</div>
<div class="Exercise">
<p>A l’aide du tableau périodique, indiquez quel sera l’ion stable formé par les éléments suivants : Na, Mg, Cl, K, Al, S, Ca, Ga.</p>
</div>
<div class="Answer">
<ul>
<li>Na : <span class="math inline">\(Na^+\)</span></li>
<li>Mg : <span class="math inline">\(Mg^{2+}\)</span></li>
<li>Cl : <span class="math inline">\(Cl^-\)</span></li>
<li>K : <span class="math inline">\(K^+\)</span></li>
<li>Al : <span class="math inline">\(Al^{3+}\)</span></li>
<li>S : <span class="math inline">\(S^{2-}\)</span></li>
<li>Ca : <span class="math inline">\(Ca^{2+}\)</span></li>
<li>Ga : <span class="math inline">\(Ga^{3+}\)</span></li>
</ul>
</div>
<div class="Exercise">
<p>Lorsqu’un électron excité d’un atome revient vers un niveau d’énergie plus bas, il émet un photon. On observe une raie d’émission de longueur d’onde 650 nm. Données : <span class="math inline">\(c = 3\cdot10^{8}\)</span> m/s, <span class="math inline">\(h = 6.625\cdot10^{-34}\)</span> J·s.</p>
<ol type="1">
<li>À quelle couleur correspond cette raie ? (voir le domaine du spectre visible) </li>
<li>Calculez la fréquence puis l’énergie du photon émis. </li>
<li>L’électron a-t-il absorbé ou émis de l’énergie ? Que représente l’énergie du photon par rapport aux niveaux de l’électron ? </li>
<li>Une autre raie du même atome a une longueur d’onde de 400 nm. Le photon correspondant est-il plus ou moins énergétique que celui à 650 nm ? Justifiez sans calcul. </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>650 nm correspond au <strong>rouge</strong>.</li>
<li><span class="math display">\[
\nu = \frac{c}{\lambda} = \frac{3\cdot10^{8}}{6.50\cdot10^{-7}} = 4.62\cdot10^{14} \text{ Hz}
\]</span> <span class="math display">\[
E = h\cdot\nu = 6.625\cdot10^{-34}\cdot4.62\cdot10^{14} = 3.06\cdot10^{-19} \text{ J}
\]</span></li>
<li>L’électron a <strong>émis</strong> de l’énergie, puisqu’il est revenu vers un niveau plus bas. L’énergie du photon est égale à la différence d’énergie entre les deux niveaux.</li>
<li>Plus <strong>énergétique</strong> : une longueur d’onde plus courte (400 nm) correspond à une fréquence plus élevée, donc à une énergie plus grande, car <span class="math inline">\(E = h\cdot c/\lambda\)</span> augmente quand <span class="math inline">\(\lambda\)</span> diminue.</li>
</ol>
</div>
<div class="Exercise">
<p>On étudie l’élément soufre (S, Z = 16). À l’aide du tableau périodique, déterminez :</p>
<ol type="1">
<li>sa période et son groupe ; </li>
<li>sa configuration électronique complète et simplifiée ; </li>
<li>son nombre d’électrons de valence ; </li>
<li>sa structure de Lewis (nombre de points, paires et célibataires) ; </li>
<li>l’ion stable qu’il forme, en justifiant par la règle de l’octet. </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>Période 3, groupe VI.</li>
<li>Complète : <span class="math inline">\(1s^{2}\,2s^{2}\,2p^{6}\,3s^{2}\,3p^{4}\)</span> ; simplifiée : [Ne]<span class="math inline">\(\,3s^{2}\,3p^{4}\)</span>.</li>
<li>6 électrons de valence (groupe VI).</li>
<li>6 points autour du symbole : 2 paires et 2 célibataires (2p 2c).</li>
<li>Le soufre gagne 2 électrons pour compléter sa couche de valence à 8 électrons (octet). Il forme l’ion <strong><span class="math inline">\(S^{2-}\)</span></strong>, isoélectronique avec l’argon.</li>
</ol>
</div>
<div class="Exercise">
<p>On considère les éléments suivants : soufre (S), chlore (Cl), potassium (K) et calcium (Ca).</p>
<ol type="1">
<li>Donnez l’ion stable formé par chacun de ces éléments. </li>
<li>Pour chaque ion, indiquez son nombre d’électrons. </li>
<li>Ces quatre ions ont-ils quelque chose en commun ? Avec quel gaz rare sont-ils isoélectroniques ? </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li><span class="math inline">\(S^{2-}\)</span>, <span class="math inline">\(Cl^{-}\)</span>, <span class="math inline">\(K^{+}\)</span> et <span class="math inline">\(Ca^{2+}\)</span>.</li>
<li>Nombre d’électrons de chaque ion :
<ul>
<li><span class="math inline">\(S^{2-}\)</span> : <span class="math inline">\(16 + 2 = 18\)</span> électrons</li>
<li><span class="math inline">\(Cl^{-}\)</span> : <span class="math inline">\(17 + 1 = 18\)</span> électrons</li>
<li><span class="math inline">\(K^{+}\)</span> : <span class="math inline">\(19 - 1 = 18\)</span> électrons</li>
<li><span class="math inline">\(Ca^{2+}\)</span> : <span class="math inline">\(20 - 2 = 18\)</span> électrons</li>
</ul></li>
<li>Les quatre ions possèdent tous <strong>18 électrons</strong> : ils sont <strong>isoélectroniques</strong> entre eux et avec l’<strong>argon</strong> (Z = 18), dont la couche de valence respecte l’octet.</li>
</ol>
</div>
<div class="Exercise">
<p>On compare trois rayonnements électromagnétiques par leur longueur d’onde : une onde radio (1 m), une lumière visible bleue (450 nm) et un rayon X (<span class="math inline">\(1\cdot10^{-10}\)</span> m). Données : <span class="math inline">\(c = 3\cdot10^{8}\)</span> m/s, <span class="math inline">\(h = 6.625\cdot10^{-34}\)</span> J·s.</p>
<ol type="1">
<li>Classez ces trois rayonnements de la fréquence la plus basse à la plus élevée. </li>
<li>Lequel transporte les photons les plus énergétiques ? Justifiez. </li>
<li>Calculez l’énergie d’un photon de lumière bleue (450 nm). </li>
</ol>
</div>
<div class="Answer">
<ol type="1">
<li>La fréquence est inversement proportionnelle à la longueur d’onde (<span class="math inline">\(\nu = c/\lambda\)</span>). De la plus basse à la plus élevée : <span class="math display">\[
\text{onde radio (1 m)} &lt; \text{bleu (450 nm)} &lt; \text{rayon X } (1\cdot10^{-10} \text{ m})
\]</span></li>
<li>Le <strong>rayon X</strong> : il a la plus courte longueur d’onde, donc la plus haute fréquence et l’énergie par photon la plus grande (<span class="math inline">\(E = h\cdot c/\lambda\)</span>).</li>
<li><span class="math display">\[
E = \frac{h\cdot c}{\lambda} = \frac{6.625\cdot10^{-34}\cdot3\cdot10^{8}}{4.50\cdot10^{-7}} = 4.42\cdot10^{-19} \text{ J}
\]</span></li>
</ol>
</div>


</section>

</main> <!-- /main -->
<script src="html/vendor/jquery-3.7.1.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {

    var exeContainerClass = 'Exercise-container';
    var exeClass = 'Exercise';
    var ansClass = 'Answer';

    $('.' + exeContainerClass).each(function(i, el) {
      let child = $(el).children('.' + exeClass);
      child.replaceWith(child.html());
      $(el).removeClass(exeContainerClass).addClass(exeClass);
    });

    var chapterNum = $('.quarto-page-breadcrumbs .chapter-number').first().text().trim();

    $('.' + exeClass).each(function(i, el) {
      var num = chapterNum + '.' + (i + 1);
      var title = $('<div>Exercice ' + num + '</div>');
      title.addClass('Label');
      $(el).prepend(title);
    });

    $('.' + ansClass).each(function(i, el) {
      $(el).click(function() {
        $(el).slideToggle();
      });
      var button = $('<button>Solution</button>');
      button.attr('type', 'button');
      button.addClass('Answer-button');
      button.click(function() {
        $(el).slideToggle();
      });
      button.insertBefore(el);
    });

  });
</script>
<script type="text/javascript">
  $(document).ready(function () {
    $("main.content table, main.content .math.display").each(function (i, el) {
      let parent = $("<div>").attr("style", "overflow-x:auto");
      $(el).wrap(parent);
    });
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./50-atome.html" class="pagination-link" aria-label="L'atome">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">L’atome</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./70-liaisons.html" class="pagination-link" aria-label="Molécules et liaisons chimiques">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Molécules et liaisons chimiques</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>