project:
  type: book
  execute-dir: project

book:
  title: "Cours de chimie générale"
  output-file: "chimie-generale"
  author:
    - "M. Michele Rizzello"
    - "(Gymnase d'Etoy)"
  date: today
  date-format: "DD.MM.YYYY"
  description: "Support du cours de chimie générale | Maturité gymnasiale"
  sidebar:
    style: docked
    background: "#fafafa"
    tools:
      - icon: file-earmark-pdf
        href: chimie-generale.pdf
        text: "Télécharger le PDF"
        target: _blank
  chapters:
    - index.qmd
    - 10-introduction.qmd
    - 20-etats-de-la-matiere.qmd
    - 30-melanges-corps-purs.qmd
    - 40-historique.qmd
    - 50-atome.qmd
    - 60-tableau-periodique.qmd
    - 70-liaisons.qmd
    - 80-molecules.qmd
    - 90-nomenclature.qmd
    - 100-solutions-electrolytes.qmd
    - 110-reactions-chimiques.qmd
    - 120-types-reactions.qmd
    - 130-stoechiometrie.qmd
    - 140-gaz-parfaits.qmd
    - 150-cinetique.qmd
    - 160-equilibres.qmd
    - 170-acides-bases.qmd
    - 180-ph-potentiel-hydrogene.qmd
    - 190-produit-solubilite.qmd
    - 200-oxydoreductions.qmd
    - 210-electrochimie.qmd
    - 220-thermochimie.qmd
    - 230-thermodynamique.qmd
    - 00-references.qmd

lang: fr

bibliography: references.bib
biblio-style: apalike
link-citations: true

crossref:
  chapters: true

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 700px
    css:
      - style.css
    fig-align: center
    include-in-header:
      - html/mathjax-mhchem.html
    include-after-body:
      - html/jquery-include.html
      - html/exercices.html
      - html/tables.html
  pdf:
    documentclass: book
    classoption: [openany]
    papersize: a4
    fontsize: 11pt
    geometry: margin=1in
    pdf-engine: xelatex
    keep-tex: true
    fig-align: center
    include-in-header: preamble.tex
