project:
  type: default
  execute-dir: project

lang: fr

format:
  revealjs:
    theme: white
    slide-level: 3
    incremental: false
    chalkboard: false
    controls: true
    controls-layout: bottom-right
    navigation-mode: vertical
    scrollable: true
    width: 100%
    height: 100%
    margin: 0
    min-scale: 1
    max-scale: 1
    css: custom.css
    include-in-header:
      - mathjax-mhchem.html
